### ISSUE TITLE
add argparse to remove manual code edits

### ISSUE THREAD

**Issue by Hir0ki** [aapatre/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE#1]
you can use the standard library module [argparser](https://docs.python.org/3/library/argparse.html) to get the username, password and the path to the browser webdriver and the browser type. 

This would be great so a don't have to has to change the coding.

**Comment by aapatre** [comment]
Thanks a lot for the info! I will check!

**Comment by aapatre** [comment]
Done! Created a requirements.py file to automatically install requirements.
Webdrivers are now taken care of by the webdriver-manager module.

**Comment by Hir0ki** [comment]
Greate that you automated it, but i would have used setup.py for that. Here is a [link ](https://realpython.com/lessons/structuring-python-application/) to a course that explains how to structure python applications. They explain how to use setup.py so you don't have to write a custom script. 

You also added the settings.txt file where you can put your login data, which is a great idea. Maybe you can use a config file format for that and the [configparser](https://docs.python.org/3/library/configparser.html) module to parse it. You can find guids how to use it: [here](https://www.pythonforbeginners.com/code-snippets-source-code/how-to-use-configparser-in-python) and [here](http://zetcode.com/python/configparser/)

**Comment by aapatre** [comment]
Will check and make the necessary changes. Once again, thanks for the info.
