### ISSUE TITLE
Issue a new release

### ISSUE THREAD

**Issue by fakeid30** [aapatre/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE#108]
I tested the caching feature all day locally. The code seems solid . Once we push a PR with updated README I believe we're good to post our next release.

**Comment by fakeid30** [comment]
@cullzie updating the readme. I'll do a PR now .

**Comment by cullzie** [comment]
@fakeid30 @aapatre Release done :tada: https://github.com/aapatre/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE/releases/tag/v0.3
