### ISSUE TITLE
Thank Jetbrains in README

### ISSUE THREAD

**Issue by fakeid30** [aapatre/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE#114]
As we are getting support from Jetbrains they sent me an email with this body : 

We hope that JetBrains software will be useful for your project! If you feel that our tools have helped you a great deal, we would be grateful if you could mention JetBrains' support on your project's homepage. You could do this by placing our [Logo](https://www.jetbrains.com/company/brand/logos/) and a link to JetBrains such as https://www.jetbrains.com/?from=ABC (make sure to replace ‘ABC’ with the name of your OS project, no spaces). Thanks in advance!

I think we should do this. I wonder where to put this though. What do you think @cullzie ?

**Comment by cullzie** [comment]
@fakeid30 Ye we can just add in a supporters section to the readme and in the relevant links there

**Comment by cullzie** [comment]
Done with #118
