### ISSUE TITLE
Move from print to logging module

### ISSUE THREAD

**Issue by cullzie** [aapatre/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE#120]
Move from print statements to use python logging module

This will have several benefits to users and devs:
- Creation of log file for easier bug reports
- Ability to have different levels of logging for debugging purposes (DEBUG, INFO etc...)
- Better formatting of console messages

**Comment by fakeid30** [comment]
yup sounds good to me.

**Comment by fakeid30** [comment]
maybe this is far fetched, but is it practical to publish this in pypi ?

**Comment by cullzie** [comment]
> maybe this is far fetched, but is it practical to publish this in pypi ?

@fakeid30 it's something that could be looked into. Maybe we could add a poll on GitHub and see what the users of the script want. Would be an easy way to prioritize features as well using this: https://gh-polls.com/

**Comment by fakeid30** [comment]
Polls look interesting

**Comment by fakeid30** [comment]
https://github.com/cool-RR/PySnooper

https://github.com/laike9m/Cyberbrain

we can use one of these to make debugging even easier .
