### ISSUE TITLE
Fix deepsource failures

### ISSUE THREAD

**Issue by cullzie** [aapatre/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE#121]
Go through any failures on deepsource and fix ones of concern.

https://deepsource.io/gh/aapatre/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE/run/b2880128-858d-4390-901e-03cf86cb0a10/python/

Having the red `x` beside the repo is upsetting :laughing:

**Comment by fakeid30** [comment]
wow @cullzie you've been working lad.

I've asked Antariksh to remove deepsource since we can't access the stats anyway. 

Thank you for all the hard work.

**Comment by fakeid30** [comment]
@cullzie deepsource has been removed, I'll send a PR which removed the .toml file and fixes README.
