### ISSUE TITLE
Add new source ?

### ISSUE THREAD

**Issue by fakeid30** [aapatre/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE#128]
Now that we have a good base, I'd like to explore the possibility of adding new source. What do you think @cullzie ?

**Comment by fancy-investigator** [comment]
Yeah bro it would be an excellent idea,i would be waiting fr that release

**Comment by cullzie** [comment]
@fakeid30 @fancy-investigator I'm open to new sources being requested and we can review them on a case by case basis. In some cases it might be too complex or not offer enough benefits to implement but we won't know that until we investigate the source

**Comment by supersri811** [comment]
How about https://comidoc.net/daily?

**Comment by fakeid30** [comment]
@supersri811 probably after we release 1.0.0 , we will take a loot at this.

**Comment by t2hv33** [comment]
@fakeid30 
https://www.real.discount/
I also use this in the past.

**Comment by cullzie** [comment]
@fakeid30 Adding new sources is possible but will require a re-write of the current structure. 
Might be best to refactor to allow multiple scrapers first then add new integrations as we go. It shouldn't be too hard to integrate comidoc after having a look at it.

**Comment by cullzie** [comment]
@fakeid30 The integration for comidoc has been done. Could put any new source suggestions into separate tickets. Think there has been enough functionality put into this version already. Might be time to release it :rocket:

**Comment by cullzie** [comment]
I'm not sure on the publish to pypi yet and don't have much time to dedicate to it. 
I don't think there is much left to do except fill in some info in setup.py and create an account on pypi to publish with

**Comment by cullzie** [comment]
@aapatre Are you ok with me putting in you as the author and your email in `setup.py`?
Or is there a distribution mail list we could add in for the email?
