### ISSUE TITLE
Release 1.0.0

### ISSUE THREAD

**Issue by fakeid30** [aapatre/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE#129]
Since we are using semver the next version should be 1.0.0. I don't think there will be any breaking change. So no point continuing the 0.* branch.

What's your opinion about it @cullzie ?

But I am not sure what to add / change before making it to 1.0.0. 

Should we try to get a GUI running ? Where someone will post their username , pass and all the other stuff. 

Not sure how necessary the GUI is though.

**Comment by cullzie** [comment]
I think the CLI works fine so a GUI adds extra complexity and dependencies that aren't really adding new functionality. Maybe working on the CLI options mentioned in #33 would be a good thing to add then realise v1

**Comment by fakeid30** [comment]
yup CLI for now should be good

**Comment by fakeid30** [comment]
@cullzie any more blocking changes ? I can't think of any.

**Comment by cullzie** [comment]
@fakeid30 Nothing more from me

**Comment by fakeid30** [comment]
@cullzie when do we release ?

**Comment by fakeid30** [comment]
I say we give this 2-3 more days to check then release on Saturday ?
