### ISSUE TITLE
Refactor opportunity ?

### ISSUE THREAD

**Issue by fakeid30** [aapatre/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE#133]
https://github.com/aapatre/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE/blob/1dae823479cd0a38c23f65eca6a3fd7ecf502f22/core/udemy.py#L186

I think this code block needs to be declared in a variable and used somewhere. From what I can see, this seems to lay dormant there without any purpose. Might be I am missing something though.

**Comment by cullzie** [comment]
@fakeid30 It is being used in the next webdriverwait but there are redundant parentheses on this wait and a redundant call to .text that I spotted before that can be removed 👍

**Comment by fakeid30** [comment]
Alright!
