### ISSUE TITLE
Typo on readme with settings.py

### ISSUE THREAD

**Issue by cpxPratik** [aapatre/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE#134]
There is typo on Instructions section of [readme](https://github.com/aapatre/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE#instructions) with `sample_settings.yaml to settings.py `. It should be `settings.yaml`.

**Comment by fakeid30** [comment]
Thanks for the report. Fixed.
