### ISSUE TITLE
 ModuleNotFoundError: No module named 'ruamel'

### ISSUE THREAD

**Issue by vaibhavpacharya** [aapatre/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE#135]
I am getting following error

```
from ruamel.yaml import YAML, dump
ModuleNotFoundError: No module named 'ruamel'

```

even though i ran pip install -r requirements.txt and installed ruamel separately as well.
My python version is Python 3.8.5. Please help.

**Comment by fakeid30** [comment]
@vaibhavpacharya what is your operating system? Can you update your python to 3.8.6 and retry ?

**Comment by fakeid30** [comment]
This also happens when your pip is older, please update pip as well.

**Comment by vaibhavpacharya** [comment]
> @vaibhavpacharya what is your operating system? Can you update your python to 3.8.6 and retry ?

Its Mac OS Catalina 10.15.6. i upgraded to python 3.9. Still seeing the same error.

**Comment by vaibhavpacharya** [comment]
> This also happens when your pip is older, please update pip as well.

Using pip 20.2.4

**Comment by fakeid30** [comment]
Ok , do these : 

1. Install "ruamel.yaml"
2. Try using poetry instead of pip 

Report back your finding afterwards please.

**Comment by fakeid30** [comment]
@vaibhavpacharya any update ?
