### ISSUE TITLE
Introduce unit test and/or CI/CD

### ISSUE THREAD

**Issue by ethankrein** [aapatre/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE#14]
Creating an issue based on the comment posted by @fakeid30 in #11.

This looks like good change. @aapatre can we introduce unit test and / or CI/CD  so we know changes work before merging?
https://www.lambdatest.com/blog/automated-testing-pipeline-with-gitlab-ci-cd-and-selenium/

**Comment by aapatre** [comment]
Lemme check

**Comment by fakeid30** [comment]
https://dev.to/seleniumbase/running-browser-tests-from-github-workflows-with-seleniumbase-1oic

This is an easier way to do it using github action.

**Comment by cullzie** [comment]
Hey,
I've created a PR which partially addresses this. Its more of a smoke test. Currently working with chrome

**Comment by fakeid30** [comment]
@cullzie shall we close this ?

**Comment by cullzie** [comment]
@fakeid30 Ye I suppose we can if it covers what was originally wanted. We can just expand on the base that is there as the project moves forward
