### ISSUE TITLE
[FEATURE REQUEST] Remove all different browsers and have only one entrypoint ? 

### ISSUE THREAD

**Issue by fakeid30** [aapatre/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE#141]
**Is your feature request related to a problem? Please describe.**

Remove all different browsers and have only one entrypoint . This is something that is eventually needed when publishing to pypi.

**Comment by fakeid30** [comment]
@cullzie share your thoughts 👍🏽

**Comment by cullzie** [comment]
Ye the ground work is already there just need to remove the other scripts. This would break peoples usage though so we'd need to make it clear to move from `udemy_enroller_chrome.py` to `udemy_enroller.py --browser=chrome`

**Comment by fakeid30** [comment]
Peak semver right there 💯

**Comment by cullzie** [comment]
@fakeid30 Actually it might make sense to add in a deprecation warning for this release when those scripts are run. 
Then people can't say its a shock when it does get removed :smile:

**Comment by fakeid30** [comment]
Yup that's more logical!

**Comment by cullzie** [comment]
@fakeid30 Do we want to maintain the vanilla script logic? If so we will need to have a CLI arg to pass down the driver path so I haven't included it in the deprecation yet. 
Does anyone use this though?

**Comment by fakeid30** [comment]
@cullzie the vanilla is for MacOS safari. I don't think there're any safari only user.

I don't think it's good software development practice to cover niche case and add bloat. 

I suggest we remove safari and add notice that safari won't work. they can install opera, firefox or chrome.

what do you think ?

**Comment by cullzie** [comment]
@fakeid30 I'm happy to trim any fat 😅 There's no point supporting and maintaining something that's not being used.

**Comment by fakeid30** [comment]
Yup I agree
