### ISSUE TITLE
Adding a feature to the script to ask the State/Territory in India [FEATURE REQUEST]

### ISSUE THREAD

**Issue by fancy-investigator** [aapatre/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE#143]
In India ,While enrolling Udemy is requesting for the "State/Union Territory" we live for enrollment,so instead of the zipcode pls consider to add this feature in the upcoming releases

**Comment by fakeid30** [comment]
@fancy-investigator provide screenshot

**Comment by fancy-investigator** [comment]
![image](https://user-images.githubusercontent.com/71169417/100970311-a6668f00-355a-11eb-9ffe-4059d58f6656.png)

**Comment by fakeid30** [comment]
is this mandatory?

**Comment by fancy-investigator** [comment]
If we want to enroll to a course we must select the state for further enrollment,This was added recently to udemy

**Comment by fakeid30** [comment]
ok thanks for the report

**Comment by fakeid30** [comment]
1st one should work @cullzie

**Comment by cullzie** [comment]
@fakeid30 Ok cool. Does anyone know what the point of it is? Tax? But if it's free there is no tax....

**Comment by fakeid30** [comment]
Not sure, could be a legal thing like zipcode is for US.

**Comment by fakeid30** [comment]
@fancy-investigator this issue is now fixed in the develop branch . Please check that out.
