### ISSUE TITLE
[FEATURE REQUEST] Use pre commit hook

### ISSUE THREAD

**Issue by fakeid30** [aapatre/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE#144]
Can we make use of some pre commit hooks ? https://github.com/pre-commit/pre-commit-hooks

**Comment by fakeid30** [comment]
@cullzie what's your thoughts on this ?

**Comment by cullzie** [comment]
@fakeid30 I'm not familiar with these. I'm guessing they are similar to local pre-commit hooks. If that's the case I'm happy to have them added in

**Comment by fakeid30** [comment]
We need to decide which ones to use.

**Comment by fakeid30** [comment]
@cullzie closing this to open a discussion. It's more suited for that.
