### ISSUE TITLE
[BUG] Doesn't enter zip code

### ISSUE THREAD

**Issue by aconamos** [aapatre/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE#150]
**Describe the bug**
Doesn't enter zip code

**To Reproduce**
1. Chrome web driver selected

**Expected behavior**
Enters zip code

**Desktop (please complete the following information):**
Windows 10

**Additional context**

**Comment by fakeid30** [comment]
@cullzie can you reproduce ?

**Comment by fakeid30** [comment]
@aconamos I can not reproduce this. Please attach screen recording of your issue. 

Are you using the release zip or cloning from git?

**Comment by fakeid30** [comment]
finally able to reproduce, it is inputting the first zip code then skipping over the next input. Likely has something to do with timing @cullzie 

@aconamos please use a vpn and connect to a non US country from until we fix this . Thanks for reporting.

**Comment by fakeid30** [comment]
@aconamos pull the develop branch and test now please. I am closing this issue , if you have any further problem, comment here and we'll discuss further instructions.

**Comment by aconamos** [comment]
Sorry I wasn't able to reply for a while. Just read through the messages, switched to develop branch, its works fine now.
