### ISSUE TITLE
ModuleNotFoundError: No module named 'selenium'

### ISSUE THREAD

**Issue by Simkav** [aapatre/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE#151]
simkav@Simkav-PC:~/Sandbox/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE$ python udemy_enroller.py 

Traceback (most recent call last):
  File "udemy_enroller.py", line 8, in <module>
    from selenium.webdriver.remote.webdriver import WebDriver
ModuleNotFoundError: No module named 'selenium'

![screenshot_2](https://user-images.githubusercontent.com/46397494/101916956-4e6dff00-3bd0-11eb-81c6-ed26120a3c53.png)

python verison 3.8
![screenshot_3](https://user-images.githubusercontent.com/46397494/101917133-90974080-3bd0-11eb-8ffc-e19c6f1006b6.png)

pip3 list shows that i have selenium

![screenshot_1](https://user-images.githubusercontent.com/46397494/101916722-0058fb80-3bd0-11eb-92a5-ac29411d0fae.png)

i'm new to phyton, what should i do?

**Comment by supersri811** [comment]
You have 2 versions of python.
Uninstall one of them.

**Comment by fakeid30** [comment]
@Simkav you are not supposed to run the script like that , to run the generic script follow this syntax : 

`python udemy_enroller.py --browser=firefox --max-pages=10 --cache-hits=12`

**Comment by Simkav** [comment]
Thanks phyton3 and arguments help.
