### ISSUE TITLE
[BUG] zip code not always filled in

### ISSUE THREAD

**Issue by asheimo** [aapatre/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE#157]
**Describe the bug**
When running the script about 80% of the time the zip code is not filled in so it has to be done manually. 

**To Reproduce**
1. run udemy_enroller.py --browser edge
2. wait for checkout page that doesn't automatically enter zip code
3. manually enter zip code
4. click enroll

**Expected behavior**
zip code is automatically entered and no interaction is required

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Win10 Build 20277.fe_release.201207-1545
 - Edge chromium
 - Version 87.0.664.60 (Official build) (64-bit)

[settings.zip](https://github.com/aapatre/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE/files/5689840/settings.zip)

**Comment by fakeid30** [comment]
It's a fixed known bug. Please pull from the develop branch. It has a fix for this. Alternately , download a zip of the develop branch code.
