### ISSUE TITLE
[QUESTION] The program stops working after - 'Hit cache 12 times in a row' ? 

### ISSUE THREAD

**Issue by RiyuzakiNatora** [aapatre/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE#158]
It says 'Hit cache 12 times in a row' and then the browser closes. I tried clearing cache and restarting the program but it give the same error again. What can be done? 
![image](https://user-images.githubusercontent.com/72497928/102174180-d733b600-3ec2-11eb-84eb-357c2d7b9053.png)

**Comment by fakeid30** [comment]
Did you read the readme ? You can pass an argument which passes parameter that's more than 12. 

This 12 means , the script hit 12 courses that you already are enrolled in. Unlikely to find any new one.

Try again next day is best option. Or as I said, run it with argument , `-cache-hits=100` or something
