### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by hd4y2t** [aapatre/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE#160]
File "udemy_enroller.py", line 36
    def parse_args(browser=None, use_manual_driver=False) > Namespace:
                                                          ^
SyntaxError: invalid syntax

im used 
OS kubuntu 20.04
chrome Version 87.0.4280.88
python version 2.7.18
python3 version 3.8.5

**Comment by fakeid30** [comment]
@hd4y2t did you read the README ? I don't see you passing any argument to the call. Please re read the instruction and follow it exactly how we asked.

**Comment by fakeid30** [comment]
If you want to follow up post a comment here.
