### ISSUE TITLE
[FEATURE REQUEST] Move cache, settings and logs to system location

### ISSUE THREAD

**Issue by cullzie** [aapatre/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE#161]
**Is your feature request related to a problem? Please describe.**
Move the cache, settings and log files to a system location under the users directory

**Describe the solution you'd like**
This needs to be done if we want to move toward a pypi package. Otherwise the user will need to always run the script in the same directory everyday

**Describe alternatives you've considered**
Just need to decide on where it will be stored in the users system. 
This will be where any data related to running of the scripts should be kept in future. i.e. settings, cache, logs etc

**Comment by fakeid30** [comment]
So basically like a folder in user's home?

**Comment by cullzie** [comment]
> So basically like a folder in user's home?

Yep that's it exactly
