### ISSUE TITLE
[FEATURE REQUEST] Add check to ensure user is logged in to udemy correctly

### ISSUE THREAD

**Issue by cullzie** [aapatre/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE#162]
**Is your feature request related to a problem? Please describe.**
Add a check to ensure the user is logged into Udemy correctly after hitting submit on login fform

**Describe the solution you'd like**
Should just wait until some element which is only available after login is visible (e.g. user avatar)

**Describe alternatives you've considered**
Could add a sleep but waiting for the correct state is better

**Comment by fakeid30** [comment]
Yup this is good.
