### ISSUE TITLE
[QUESTION]  How can I run multiple instances?

### ISSUE THREAD

**Issue by Brblol** [aapatre/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE#166]
It seems a bit slow. Can I run multiple instances? I tried and the second window quickly existed due to hitting cache too many times. it possible to make it start at a different list?

**Comment by fakeid30** [comment]
Hitting cache too many times mean there is no more new courses to enroll you to.

**Comment by fakeid30** [comment]
If you have any more query regarding this please post a comment , and no , multiple instance is not supported natively. You have to just run it multiple times. We do not encourage or provide support for this use case.
