### ISSUE TITLE
Automatic enrollment not working. Only opens pages of courses.

### ISSUE THREAD

**Issue by Billuri** [aapatre/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE#170]
Hello,

I did everything mentioned in the requirements section. Used firefox.
First, I must say that I cannot run any other browsers than firefox. When I try with firefox, it fetches courses and starts the automation process. However, it does not enroll in any courses. Just opens udemy page, opens course pages, then does nothing. 

I expect the behavior shown in video on project page, but nope.

Before submitting this as a bug, I'd like to ask if this is a limitation of firefox, one of the issues mentioned on main page?

**Comment by fakeid30** [comment]
> Before submitting this as a bug, I'd like to ask if this is a limitation of firefox, one of the issues mentioned on main page?

I believe you are hitting one of the known bugs. This bug has been fixed in develop and due for a release sometime soon . 

If you use a vpn it will work. Try that.

**Comment by Billuri** [comment]
Thanks for the recommendation. I used VPN, but this time udemy blocked my password due to different geo-location I guess.

But one point I noticed, even though I used vpn for connection, and especially selected an English speaking country, my locale still stayed at the same local settings and I saw page in my own local language. 

There may be a problem with browser's locale settings IMHO. 
Thanks anyway. Will keep trying.

**Comment by fakeid30** [comment]
In that case I would ask you to use the develop branch.

**Comment by fakeid30** [comment]
@Billuri did this solve your issue ?

**Comment by Billuri** [comment]
@fakeid30 unfortunately, udemy keeps disabling my password when i use vpn. So vpn seems not an option for me :(

I will try with my locale changed to en-en, with development branch and no vpn. Will keep you informed.

**Comment by fakeid30** [comment]
@Billuri go to the development branch and run this command: 

`python udemy_enroller.py --tutorialbar --browser=ff`

Does it work?

**Comment by Billuri** [comment]
Hello, that is what I am typing. I will try to shoot a video and give a 
link here if it is permitted.

By the way, i managed to run the script on linux with both firefox and 
chromium. But the same things did not work in Windows with chrome or 
chromium. I will give a screenshot also.

Sorry for the delays. It's a bit busy here in the company as it is year's end.

19 Aralık 2020 18:54:48 Fake ID <notifications@github.com> yazdı:

**Comment by fakeid30** [comment]
![2020-12-20 11_53_03-Greenshot](https://user-images.githubusercontent.com/26362832/102706197-f57e2500-42b9-11eb-9071-769d36e97818.png)

@Billuri this is working on widows for me , I am using the master version.

**Comment by Billuri** [comment]
Dear @fakeid30 

This is develop branch. All the requirements are satisfied.
![install](https://user-images.githubusercontent.com/63073397/102713142-fd988d80-42d6-11eb-8815-b2e291b6d80b.PNG)

First, I tried with chromium:
![chromium](https://user-images.githubusercontent.com/63073397/102713156-10ab5d80-42d7-11eb-87ab-a324497d0bb8.PNG)

Then, I tried with FF:
![FF](https://user-images.githubusercontent.com/63073397/102713261-0178df80-42d8-11eb-8604-bf0bf8cebada.PNG)

Here is the video:
https://mega.nz/file/NmwUkBCR#le4KnfoABPN7tSTkJdoIxza7mHUaeMCnJv7bit9cLF4

**Comment by fakeid30** [comment]
@Billuri your firefox is running. You are getting the courses right? Check your email.

**Comment by Billuri** [comment]
Yes FF is running but no enrollment. I do not receive any emails regarding enrollment, nor I see it on udemy-My Learning section either :(

![Courses](https://user-images.githubusercontent.com/63073397/102713541-0fc7fb00-42da-11eb-9532-ebfc926b56a3.PNG)

**Comment by fakeid30** [comment]
Ok as a last resort change udemy pass and re run on firefox @Billuri

**Comment by Billuri** [comment]
Changed my password, used master branch and it worked! Enrolled my first course, thank you very much!

Here, I'd like to ask you one last question: When giving the desired categories to the script, do we have to use the words as they are shown on udemy (or tutorialbar), as their link form when I hover on the link  (i.e. Personal development or personal-development) ?


![category](https://user-images.githubusercontent.com/63073397/102713982-f7a5ab00-42dc-11eb-96e8-cbcf1faa7268.PNG)

(Are the categories same on both udemy or tutorialbar? I didn't check.)

**Comment by fakeid30** [comment]
Glad that it got solved @Billuri 

Try chrome as well and let us know.

Personal Development.
