### ISSUE TITLE
Resume at a given start page

### ISSUE THREAD

**Issue by hoeni** [aapatre/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE#175]
**Is your feature request related to a problem? Please describe.**
The script stopped with an error (not filing a bug because it's probably related with some of my actions). However now it stopped with 'Page: 32 of 648 scraped'

**Describe the solution you'd like**
Have command line option for 'start with page 32, please', to restart the process properly without having to scrape those 31 pages first...

**Comment by fakeid30** [comment]
@hoeni this means there are no new courses for you to get (rest are expired)
