### ISSUE TITLE
Project rename?

### ISSUE THREAD

**Issue by fakeid30** [aapatre/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE#18]
I want to see if there can be a prettier name for this project than current boring name. For example, I had "udemy-cherrypick 🍒" in my mind.

**Comment by ethankrein** [comment]
I'd support just a shortening of the name we already have.
* Automatic Udemy Course Enroller
  * This one best conveys what the project does.
* Udemy Course Enroller
* Automatic Course Enroller
  * This is too vague unless this project starts supporting other course websites.

> I had "udemy-cherrypick 🍒" in my mind.
* I don't think this name is bad, but I don't think cherrypick works in the context of the project.

**Comment by fakeid30** [comment]
> Automatic Udemy Course Enroller
> 
>     * This one best conveys what the project does.

I agree

**Comment by aapatre** [comment]
Great suggestion! So let's change the title to "Automatic Udemy Course Enroller" and the tagline to "GET Paid Courses for FREE Legally!" since the tagline attracted a lot of attention.

**Comment by fakeid30** [comment]
Yes I agree.

**Comment by ANASABDIALI** [comment]
i want t change the usernam and password
