### ISSUE TITLE
[QUESTION] why script closing after 30 redirects

### ISSUE THREAD

**Issue by biswajit1602** [aapatre/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE#183]
How can I change the script size or max cache size, i dont want to stop the script automatically because it only enroll first 3 pages of tutorialbar.

**Comment by fakeid30** [comment]
Read the instruction . You pass a command line argument like:

--max-pages=50

**Comment by biswajit1602** [comment]
Can you tell me the full command? You see I am not a programmer. Usually I just type python udemy_enroller_chrome.py in the windows power shell
