### ISSUE TITLE
[FEATURE REQUEST] Add command line argument to have custom source

### ISSUE THREAD

**Issue by hoeni** [aapatre/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE#187]
**Describe the solution you'd like**
Have a commandline option to pass the URL of a page containing Udemy URLs (like https://www.mydealz.de/deals/gns3-1724665). The Links are Udemy links with embedded voucher code, but seem to get redirected via a redirector.

**Comment by fakeid30** [comment]
This is not possible because different sites have different style. So we can't parse the URL from a custom site.

**Comment by hoeni** [comment]
Well, it could take all URLs from the page and filter them for a certain pattern using only those that match. However, If one would write the parser on its own, creating file with Udemy URLs containing the Voucher, would it be possible to have an option for reading those URLs from a file?

**Comment by fakeid30** [comment]
> if one would write the parser on its own, creating file with Udemy URLs containing the Voucher, would it be possible to have an option for reading those URLs from a file?

That can be done.
