### ISSUE TITLE
[FEATURE REQUEST] Use Numba

### ISSUE THREAD

**Issue by fikrado** [aapatre/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE#189]
# python Speed 
`is too low please use namba to make the script 10x faster`

**Comment by fakeid30** [comment]
First of all it's called Numba , not namba. 

Second of all, we are not familiar with the process of using Numba , if you want please send a PR. 

Marking this as wontfix as we lack the technical prowess to do this.

**Comment by fikrado** [comment]
ok scary clown
