### ISSUE TITLE
Hit cache 12 times in a row. Exiting script    Closing browser

### ISSUE THREAD

**Issue by Azghour-Saad** [aapatre/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE#191]
**Describe the bug**

When i run the script, the terminal exit quickly
- **python udemy_enroller_chrome.py --browser=chrome**  

**Expected behavior**
- starts enrolling me to Udemy courses.

**Desktop**
 - OS: [Windows]
 - Browser [chrome]

**Screenshots**
![exite](https://user-images.githubusercontent.com/33766249/103406596-86c38600-4b5b-11eb-80ad-2130c9ea9a02.PNG)

**Comment by fakeid30** [comment]
#158 

This is intended behavior , check the linked issue.
