### ISSUE TITLE
[BUG]Error while running comidoc scrapper: string indices must be integers

### ISSUE THREAD

**Issue by biswajit1602** [aapatre/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE#197]
python udemy_enroller.py --browser=chrome --max-pages=10
Loading existing settings

[WDM] - Current google-chrome version is 87.0.4280
[WDM] - Get LATEST driver version for 87.0.4280
[WDM] - Get LATEST driver version for 87.0.4280
[WDM] - Trying to download new driver from http://chromedriver.storage.googleapis.com/87.0.4280.88/chromedriver_win32.zip
[WDM] - Driver has been saved in cache [C:\Users\SamBunty\.wdm\drivers\chromedriver\win32\87.0.4280.88]

DevTools listening on ws://127.0.0.1:11208/devtools/browser/f6782df1-3260-4cc5-afa1-25877ca8800b
[18760:15856:0107/021401.378:ERROR:device_event_log_impl.cc(211)] [02:14:01.378] USB: usb_device_handle_win.cc:1020 Failed to read descriptor from node connection: A device attached to the system is not functioning. (0x1F)
tutorialbar scraper is running
comidoc scraper is running
Page: 1 of 679 scraped from tutorialbar.com
Got 12 links from https://www.tutorialbar.com in 6.18 seconds
comidoc scraper complete
Error while running comidoc scrapper: string indices must be integers
Successfully enrolled in: Introduction to Business Analytics | Udemy
Successfully enrolled in: Etsy Hacking Domination Bundle: SEO, Vintage & Dropshipping | Udemy
Successfully enrolled in: Regular Expressions for Beginners and Beyond! With Exercises | Udemy
Successfully enrolled in: Microsoft DP-201: Designing an Azure Data Solution (2021) | Udemy
Successfully enrolled in: Fundamentals of Control System | Udemy
Successfully enrolled in: Adobe Illustrator Mega Course - Form Beginner to Advanced | Udemy
Successfully enrolled in: AWS Networking Masterclass - Amazon VPC and Hybrid Cloud | Udemy
Successfully enrolled in: Understanding Business Model Canvas with real life examples | Udemy
tutorialbar scraper is running
Page: 2 of 679 scraped from tutorialbar.com
Got 12 links from https://www.tutorialbar.com in 4.22 seconds
Successfully enrolled in: Binge-Free Healthy Lifestyle Diet | Udemy
Successfully enrolled in: EIQ2 Coaching for Improved Performance and Superior Results | Udemy
Successfully enrolled in: Vegan Diet - Healthy Lifestyle | Udemy
Successfully enrolled in: Healthy Heart - Strengthen, Heal & Protect Your Heart | Udemy
Timeout on link: https://www.udemy.com/course/eczema-solution-treatment-tips-solution-training/?couponCode=D532A03C39B91B0B2BE7
Successfully enrolled in: The Simple And Easy Way To Cure Insomnia: Sleep Better! | Udemy
Successfully enrolled in: S Corporation Income Tax - Form 1120S | Udemy
Successfully enrolled in: Ketogenic Diet – Look & Feel Amazing The Keto Diet Way! | Udemy
tutorialbar scraper is running
Page: 3 of 679 scraped from tutorialbar.com
Got 12 links from https://www.tutorialbar.com in 3.77 seconds
Successfully enrolled in: Complete Email Writing Communication Skills Bootcamp 2021 | Udemy
Successfully enrolled in: Design The Best Advertising Material From Scratch | Udemy
Successfully enrolled in: Futures Trading Mastery 2021 | FREE Top 45 Trading Signals! | Udemy
Successfully enrolled in: Goal Settings For A Successful Life: Simple & Easy! | Udemy
Successfully enrolled in: Find Dream Job & Build Your Career Using Best Interview Sk | Udemy
--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\Programs\Python\Python39\lib\logging\__init__.py", line 1082, in emit
    stream.write(msg + self.terminator)
  File "C:\Users\Programs\Python\Python39\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2714' in position 143: character maps to <undefined>
Call stack:
  File "C:\Users\Desktop\Udemy-Course-Enroller\Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE-develop\udemy_enroller.py", line 4, in <module>
    main()
  File "C:\Users\Desktop\Udemy-Course-Enroller\Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE-develop\scripts\udemy_enroller.py", line 116, in main
    run(args.browser, tutorialbar_enabled, comidoc_enabled, args.max_pages)
  File "C:\Users\Desktop\Udemy-Course-Enroller\Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE-develop\scripts\udemy_enroller.py", line 57, in run
    redeem_courses(dm.driver, settings, tutorialbar_enabled, comidoc_enabled, max_pages)
  File "C:\Users\Desktop\Udemy-Course-Enroller\Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE-develop\core\runner.py", line 89, in redeem_courses
    _redeem_courses(driver, settings, scrapers)
  File "C:\Users\Desktop\Udemy-Course-Enroller\Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE-develop\core\runner.py", line 42, in _redeem_courses
    status = udemy_actions.redeem(course_link)
  File "C:\Users\Desktop\Udemy-Course-Enroller\Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE-develop\core\udemy.py", line 240, in redeem
    logger.info(f"Successfully enrolled in: {course_name}")
Message: 'Successfully enrolled in: Pictures and Videos colorization by Artificial Intelligence✔ | Udemy'
Arguments: ()
Successfully enrolled in: Pictures and Videos colorization by Artificial Intelligence✔ | Udemy
Successfully enrolled in: Modern Multi Vendors E-Commerce Store In PHP | Udemy
Successfully enrolled in: Intermittent Fasting 101 - The Beginner's Guide | Udemy
Successfully enrolled in: Learn Swedish for Beginners: The Ultimate 150-Lesson Course | Udemy
tutorialbar scraper is running
Page: 4 of 679 scraped from tutorialbar.com
Got 12 links from https://www.tutorialbar.com in 3.99 seconds
Successfully enrolled in: Self Motivation Through Fulfillment For Sustained Motivation | Udemy
Successfully enrolled in: Public Speaking: You Can be a Great Speaker within 24 Hours | Udemy
Successfully enrolled in: Immunity Boosting Foods - Protect & Boost Your Immune System | Udemy
Successfully enrolled in: Overcoming Biggest Challenges to Business Success Fast | Udemy
Timeout on link: https://www.udemy.com/course/how-to-successfully-work-from-home/?couponCode=B5ED0085EB32403FF029
tutorialbar scraper is running
Page: 5 of 679 scraped from tutorialbar.com
Got 12 links from https://www.tutorialbar.com in 3.61 seconds
Successfully enrolled in: Data Manipulation in Python: A Pandas Crash Course | Udemy
Successfully enrolled in: Blender 2.8 Bootcamp - Learn 3D, EEVEE, Collections & More | Udemy
Successfully enrolled in: Fundamentals of IoT (Internet of Things) | Udemy
Successfully enrolled in: Passive Income 2021 | Resell eBooks Online | Work From Home | Udemy
Successfully enrolled in: Entrepreneurial Finance: Venture Capital | Udemy
Successfully enrolled in: Build Responsive website using HTML5, CSS3 and Javascript | Udemy
Successfully enrolled in: (2021) Economic Analysis of “Sales” | Udemy
Successfully enrolled in: React Native bootcamp - Build an Instagram Clone w/Firebase | Udemy
tutorialbar scraper is running
Page: 6 of 679 scraped from tutorialbar.com
Got 12 links from https://www.tutorialbar.com in 4.36 seconds
Successfully enrolled in: QuickBooks Desktop Not for Profit Organizations | Udemy
Successfully enrolled in: SEO 2021 - Learn Local Seo to Make Your Site Rank Higher | Udemy
Successfully enrolled in: EQ-2 Resilience and Mental Strength - Emotional Intelligence | Udemy
Successfully enrolled in: Emotional Intelligence 2 - Confidence and Career Mastery | Udemy
Successfully enrolled in: EIQ-2 Smart Business - Emotional Intelligence for Excellence | Udemy
Successfully enrolled in: Advanced IT Troubleshooting for Helpdesk Support Technicians | Udemy
tutorialbar scraper is running
Page: 7 of 679 scraped from tutorialbar.com
Got 12 links from https://www.tutorialbar.com in 3.50 seconds
Successfully enrolled in: QuickBooks Desktop Job Costing | Udemy
Successfully enrolled in: CSS3 and Bootstrap for Absolute Beginners : 4 courses in 1 | Udemy
Successfully enrolled in: Bank Feeds-QuickBooks Online, Xero, Sage, Wave (Comparison) | Udemy
tutorialbar scraper is running
Page: 8 of 679 scraped from tutorialbar.com
Got 12 links from https://www.tutorialbar.com in 3.79 seconds
Timeout on link: https://www.udemy.com/course/professional-school-of-photography-from-begginer-to-master/?couponCode=DB2EB8AAE34C7B49BD4D
tutorialbar scraper is running
Page: 9 of 679 scraped from tutorialbar.com
Got 12 links from https://www.tutorialbar.com in 3.22 seconds
tutorialbar scraper is running
Page: 10 of 679 scraped from tutorialbar.com
Stopping loop. We have reached max number of pages to scrape: 10
tutorialbar scraper complete
Got 12 links from https://www.tutorialbar.com in 2.28 seconds
All scrapers complete
Closing browser

**Comment by cullzie** [comment]
Should be fixed with this: #195
