### ISSUE TITLE
[BUG]Scraper is running but Got 0 links from https://comidoc.net, 

### ISSUE THREAD

**Issue by biswajit1602** [aapatre/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE#199]
**DevTools listening on ws://127.0.0.1:1969/devtools/browser/d06d0ea5-4cdf-4f1b-b1bd-a00311dd6252
[11120:11340:0107/230019.730:ERROR:device_event_log_impl.cc(211)] [23:00:19.730] USB: usb_device_handle_win.cc:1020 Failed to read descriptor from node connection: A device attached to the system is not functioning. (0x1F)
[11120:11340:0107/230019.731:ERROR:device_event_log_impl.cc(211)] [23:00:19.731] USB: usb_device_handle_win.cc:1020 Failed to read descriptor from node connection: A device attached to the system is not functioning. (0x1F)**
tutorialbar scraper is running
comidoc scraper is running
**Page: 1 of 16 scraped from comidoc.net
Got 0 links from https://comidoc.net in 2.63 seconds**
Page: 1 of 681 scraped from tutorialbar.com
Got 12 links from https://www.tutorialbar.com in 6.76 seconds
tutorialbar scraper is running
comidoc scraper is running
Page: 2 of 16 scraped from comidoc.net
Got 0 links from https://comidoc.net in 1.19 seconds
Page: 2 of 681 scraped from tutorialbar.com
Got 12 links from https://www.tutorialbar.com in 9.30 seconds
Timeout on link: https://www.udemy.com/course/complete-progressive-web-app-bootcamp/?couponCode=CDF9DD8B1745E432747D
Successfully enrolled in: Heighten Consciousness of Self. Build Self-Esteem.Be Happier | Udemy
Successfully enrolled in: Twitter Marketing: 1000% Engagement & More Twitter Followers | Udemy
Successfully enrolled in: 10 Passive Income Businesses - Earn Passive Income In 2021 | Udemy
Successfully enrolled in: DIY Advance Options Trading Strategies (5 Courses) 11 Hours | Udemy
Successfully enrolled in: Android Penetration Testing | Udemy
Timeout on link: https://www.udemy.com/course/automate/?couponCode=JAN2021FREE
Successfully enrolled in: Practical Web Development: 22 Courses in 1 | Udemy
Successfully enrolled in: Complete NodeJS course with express, socket io and MongoDB | Udemy
tutorialbar scraper is running
comidoc scraper is running
Page: 3 of 681 scraped from tutorialbar.com
Got 12 links from https://www.tutorialbar.com in 4.54 seconds
Page: 3 of 16 scraped from comidoc.net
Got 0 links from https://comidoc.net in 18.24 seconds
Timeout on link: https://bit.ly/35yApqL
Successfully enrolled in: Complete Modern JavaScript Firebase BootCamp the beginner | Udemy
Successfully enrolled in: Code with Node JS - 2020 | Udemy
Successfully enrolled in: Mastering The Complete Agile Scrum Master Workshop | Udemy
Timeout on link: https://www.udemy.com/course/time-management-for-students-professionals-entrepreneurs/?couponCode=8FEA2B50EB444DBEFB3B
Successfully enrolled in: RASA :Build and Deploy Your Chatbot On The Cloud (100% FREE) | Udemy
Successfully enrolled in: Internationally Accredited Diploma in Keto Dietary Advisor | Udemy
tutorialbar scraper is running
comidoc scraper is running
Page: 4 of 16 scraped from comidoc.net
Got 0 links from https://comidoc.net in 1.52 seconds
Page: 4 of 681 scraped from tutorialbar.com
Got 12 links from https://www.tutorialbar.com in 5.21 seconds
tutorialbar scraper is running
comidoc scraper is running
Page: 5 of 681 scraped from tutorialbar.com
Page: 5 of 16 scraped from comidoc.net
Got 0 links from https://comidoc.net in 2.51 seconds
Got 12 links from https://www.tutorialbar.com in 4.57 seconds
tutorialbar scraper is running
comidoc scraper is running
Page: 6 of 681 scraped from tutorialbar.com
Page: 6 of 16 scraped from comidoc.net
Got 0 links from https://comidoc.net in 1.69 seconds
Got 12 links from https://www.tutorialbar.com in 3.62 seconds
tutorialbar scraper is running
comidoc scraper is running
Page: 7 of 16 scraped from comidoc.net
Got 0 links from https://comidoc.net in 1.06 seconds
Page: 7 of 681 scraped from tutorialbar.com
Got 12 links from https://www.tutorialbar.com in 4.42 seconds
tutorialbar scraper is running
comidoc scraper is running
Page: 8 of 16 scraped from comidoc.net
Got 0 links from https://comidoc.net in 1.21 seconds
Page: 8 of 681 scraped from tutorialbar.com
Got 12 links from https://www.tutorialbar.com in 4.56 seconds
tutorialbar scraper is running
comidoc scraper is running
Page: 9 of 16 scraped from comidoc.net
Got 0 links from https://comidoc.net in 0.96 seconds
Page: 9 of 681 scraped from tutorialbar.com
Got 12 links from https://www.tutorialbar.com in 4.75 seconds
tutorialbar scraper is running
comidoc scraper is running
Page: 10 of 681 scraped from tutorialbar.com
Page: 10 of 16 scraped from comidoc.net
Stopping loop. We have reached max number of pages to scrape: 10
comidoc scraper complete
Got 0 links from https://comidoc.net in 1.30 seconds
Stopping loop. We have reached max number of pages to scrape: 10
tutorialbar scraper complete
Got 12 links from https://www.tutorialbar.com in 5.83 seconds
All scrapers complete
Closing browser

**Comment by fakeid30** [comment]
@biswajit1602 this is fixed in development , please pull from there.

**Comment by cullzie** [comment]
@biswajit1602 Comidoc API changed again. Issue is noted here: #201
