### ISSUE TITLE
[BUG] Comidoc API has changed

### ISSUE THREAD

**Issue by cullzie** [aapatre/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE#201]
**Describe the bug**
Comidoc API has changed.

**To Reproduce**
Run the script
Getting 0 links from comidoc

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser: Chrome

**Comment by fakeid30** [comment]
Again ? Oh my !

**Comment by cullzie** [comment]
Ye it might be time to cut our losses on it since its changing almost daily

**Comment by fakeid30** [comment]
Might as well!

**Comment by fakeid30** [comment]
I don't understand why they keep changing API daily . WTF!

**Comment by cullzie** [comment]
Think it is just active dev. Seems like the site is improving with each release. Not much point in scraping from it though as it is not yet in a stable state

**Comment by fakeid30** [comment]
☹

**Comment by lamtonylam** [comment]
Yes, not working Comidoc

**Comment by fakeid30** [comment]
@cullzie what do we do about releasing v2 now ? I was thinking we can disable the comidoc from default run and enable it explicitly with a flag ?

**Comment by cullzie** [comment]
Ye that's what I was thinking. Although it being broken won't stop the other scrapers working as expected. I'll try fix it early this week and leave it until next weekend to check that it's stable before we release. Does that sound good?

**Comment by fakeid30** [comment]
@cullzie perfect
