### ISSUE TITLE
error on line 15 of udemy_enroller.py

### ISSUE THREAD

**Issue by Gamesgalor05** [aapatre/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE#202]
pi@raspberrypi:~/udemy $ python udemy_enroller.py --browser=chromium
  File "udemy_enroller.py", line 15
    browser: str,
                 ^

cd udemy
python requirements.py
python udemy_enroller.py --browser=chromium

 - OS: Raspbian
 - Browser chromium

I am not sure why this would happen but it could have to do with me renaming the file to "udemy" instead so that I could just easily type it into the terminal instead of typing the whole thing (I am extremely new to this kind of stuff and have very basic knowledge of the terminal and python, sorry if this is just me making a mistake)

**Comment by fakeid30** [comment]
Renaming anything is not supported. Sorry. Use tab to autocomplete. Or you can use fish or oh my zsh which will also offes autocomplete full name.
