### ISSUE TITLE
Readme.md update

### ISSUE THREAD

**Issue by Deejuha** [aapatre/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE#205]
Hello, at the at the beginning I want to say thank you for your great work for a project!

May I suggest a small readme updates?

1.  Deprecation warnings
``` Choose the appropriate file for your browser (from the list below): ``` currently usage of those script is deprecated. I believe description shall contain only the `udemy_enroller.py` script usage.

2. When runs Udemy in a language different than English, the script parameters (like category or course language) shall be written in correlated Udemy language. IMHO it's good point just to leave it somewhere in the instruction.

**Comment by fakeid30** [comment]
Hey @Deejuha , good evening. Thank you for your nice suggestions. 

1. The readme has been updated in development branch and will be updated when we release the next version. We are waiting to see if comidoc changes anything again. 
2. Different language is not supported and it will be mentioned, yes. Thanks for pointing it out.

**Comment by fakeid30** [comment]
@Deejuha this should be fixed now, please take a look and let us know.

**Comment by Deejuha** [comment]
I've considered this as close - thanks :)

**Comment by Deejuha** [comment]
Basically it's working, but the parameters passed in `settings.yml` should be in origin language.
```
  categories: [Programowanie,IT i oprogramowanie,Muzyka]
  languages: [Angielski,Polski]
```

**Comment by fakeid30** [comment]
So should we mention "non english inputs are not supported. Consider using them at your own risk"?

**Comment by Deejuha** [comment]
Well, IMHO prettier and nicer would be `Non-English inputs are not supported, but as a workaround try to pass parameters in your udemy language.`

Wondering if not so supported, haven't looked into the code but it seems like those group names are inherited from udemy itself.

**Comment by fakeid30** [comment]
@cullzie opinion?

**Comment by fakeid30** [comment]
@Deejuha if we mention that they can use the text in their own language, there's gonna be some weird issues that we can't tackle sooner or later.

Also yes, they are inherited from udemy itself.

**Comment by cullzie** [comment]
The values are inherited from udemy so if you are using udemy in Spanish the values in settings.yaml should be in Spainish. 
Ye it just needs to be clearer in the README.md that the values in settings.yaml should be in the same language as the site you are browsing on

**Comment by Deejuha** [comment]
@fakeid30 do you agree with that?
Shall I reopen / do the CR?

**Comment by fakeid30** [comment]
@Deejuha i already changed it. Check it out.

**Comment by Deejuha** [comment]
right! apologises!

**Comment by fakeid30** [comment]
@Deejuha wszystko dobrze, nie ma się czym martwić. nie ma potrzeby przepraszać. Mam nadzieję, że wszystko było w porządku? Jeśli w przyszłości okaże się, że wszystko jest w porządku, podawaj więcej sugestii.
