### ISSUE TITLE
Cache 12 times in a row and exit script

### ISSUE THREAD

**Issue by BazioDEV** [aapatre/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE#209]
Hit cache 12 times in a row. Exiting script
Closing browser

**Comment by fakeid30** [comment]
This means the script can not find any more courses for you today. It's explained in the README. So you should already know this. I am closing this. 

To remedy this you need to run the script again tomorrow. 

Comment if you have any further question.
