### ISSUE TITLE
[BUG] Can't run the script

### ISSUE THREAD

**Issue by Splintdewolfcry** [aapatre/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE#215]
Hello,
I am using Win 10 build 18363. I have been trying to run the code from visual studio code and in the problems sections, I have this: No name 'cli' in module 'udemy_enroller' and when I try to run the code itself with chrome or firefox, https://ibb.co/zSfpZyn it does not show any errors but in the video it was different so I could use a bit of a help. Lastly, I can't install this through Pypi, my computer somehow does not allow me to do so, maybe this bit of information could help.
Kind Regards,
Sarp

**Comment by fakeid30** [comment]
The browser is called google-chrome, not chrome. We need detail info for why it does not work in pip. Please provide detail info like series of screenshots with steps outlined.

**Comment by cullzie** [comment]
@Splintdewolfcry It could be possible that you have pip using python2 on your env. 
Try installing with `pip3 install udemy_enroller` so that you are sure you are using the correct version of python (Python 3)

**Comment by cullzie** [comment]
@Splintdewolfcry If you are running from the repo directly you still need to run the script as before:
`python udemy_enroller.py --browser=chrome`

You can only invoke `udemy_enroller --browser=chrome` if you have installed via PyPi.
