### ISSUE TITLE
[FEATURE REQUEST] Implement a GUI with Gooey

### ISSUE THREAD

**Issue by fakeid30** [aapatre/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE#219]
I came across this : https://github.com/chriskiehl/Gooey 

@cullzie what do you think about this?

**Comment by fakeid30** [comment]
![Screenshot from 2021-01-24 23-15-30](https://user-images.githubusercontent.com/26362832/105637901-1a0d8400-5e9a-11eb-8f80-318c6c0a0302.png)

Working on my local install. Need to iron out few bugs.

**Comment by fakeid30** [comment]
On further tinkering, the biggest hurdle I have come across is compiling WxPython takes about 30 minutes on linux. The reason is this:

> Because of the differences between Linux distributions (mainly different versions of the core libraries installed by default, but also platform architecture and etc.) it is not possible to host binary wheel files for Linux on PyPI unless they can be made to work within the constraints of PEP 513 Unfortunately, attempts to pound the wxPython peg into the manylinux1 hole have not been very successful. Maybe manylinux2 will be a better fit. In the meantime, if you have a Linux similar enough to those used to build the wheels located under the wxPython Extras linux folder, then you can use them and not need to build the wheels yourself.

Not sure how to overcome this.

**Comment by cullzie** [comment]
This looks nice :100: Would need to iron out the issues you highlighted though or find a similar solution that is more portable

**Comment by fakeid30** [comment]
this became irrelevant with our alpha branch change. So i am closing it
