### ISSUE TITLE
Add cli option to remove/reset stored settings

### ISSUE THREAD

**Issue by samrose3** [aapatre/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE#222]
**Is your feature request related to a problem? Please describe.**
I wanted to use a different login for Udemy but couldn't figure out how to reset the stored settings info. I dug around the source code to understand where the settings were being kept.

After finding and removing the `~/.udemy_enroller` folder, I see that the cli does state that the settings are stored there when created, but I didn't notice or remember that message after using the cli the first time.

**Describe the solution you'd like**
It would be convenient to have a cli command or flag (ex: `--reset`) that would remove the stored settings and allow the user to reset new info.

**Describe alternatives you've considered**
Alternatively, maybe have a section on removing the settings in the `--help` message.

**Additional context**
None

**Comment by Deejuha** [comment]
I'm not aware if cyber security engineer will blow me up, but how about passing credentials as an optional parameters in order to override `~.\udemy_enroller\settings.yaml` parameters?

**Comment by fakeid30** [comment]
@samrose3 good idea, this can be done. @cullzie what do you think?

@Deejuha personally, not a fan of this approach.

**Comment by cullzie** [comment]
@fakeid30 Ye this idea had crossed my mind before but just never got around to adding it in. Would be a straightforward change.
@Deejuha If we can remove the original one there shouldn't be need to override really. If there are a lot of people with multiple profiles then having an override or choice between multiple settings files might be a useful option

**Comment by fakeid30** [comment]
Fixed with #224
