### ISSUE TITLE
[FEATURE REQUEST] Add stats at end of run

### ISSUE THREAD

**Issue by cullzie** [aapatre/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE#223]
**Describe the solution you'd like**
Add some information in tabular format at the end of a run

Could contain info such as:

- Number of courses enrolled
- Savings ($420 saved)
- Number of courses scraped
- Average enrol time
- Average scrape time
- Already enrolled count
- Coupon expired count

**Describe alternatives you've considered**
Plenty of libraries which print tables nicely in the terminal Eg. https://pypi.org/project/tabulate/

**Additional context**

**Comment by fakeid30** [comment]
This is a fantastic idea.

**Comment by jlarini** [comment]
I'm working on it by now :)
