### ISSUE TITLE
[BUG] Not enough time to solve captcha

### ISSUE THREAD

**Issue by fakeid30** [aapatre/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE#233]
**Describe the bug**
When I am invoking this script, it is taking me to a captcha, but logging in normally is not getting any captcha. When I am seeing the captcha, there is not enough time to solve the problem. 

**To Reproduce**
1. run script
2. see error (see screenshot)

**Expected behavior**
The window would hold until the captcha is solved

**Screenshots**
![Screenshot from 2021-02-10 09-57-08](https://user-images.githubusercontent.com/26362832/107462622-b1efbb00-6b86-11eb-9903-984e938d14e0.png)
![Screenshot from 2021-02-10 09-57-14](https://user-images.githubusercontent.com/26362832/107462657-c92ea880-6b86-11eb-9cd5-ea94f28cd059.png)

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Browser: Firefox 
 - Version: 85.0.1
  
**Additional context**
This is the same reason github CI is failing as well.

**Comment by tylkofarci** [comment]
This is not google captcha  on udemy site, this is separate cloudflare captcha.

**Comment by biswajit1602** [comment]
Same problem here

**Comment by cullzie** [comment]
Ye the captcha has changed. I've updated the code to allow the user solve it but I still could not progress beyond the captcha check

**Comment by khdan** [comment]
same here!

**Comment by yaasin12** [comment]
same here, it wont accept the captcha

**Comment by cullzie** [comment]
I have a possible fix for this which is a big change to the code base so I need a while to test it fully.
The premise of the change is just to login and enrol via the REST api. This would remove the dependency on browsers and improve the speed.
However this is a pretty significant change so it may take time to iron out any issues with it. 

@fakeid30 Do you think we could create a develop_beta branch. Can merge things into that and people can test it from there. Don't want to merge to develop and make things worse :smile:

**Comment by fakeid30** [comment]
@cullzie just create an alpha branch, since develop branch is already kind of a beta.

**Comment by cullzie** [comment]
Possible fix for this is on alpha branch now.
If anyone could test and report back any issues that would be great. Thanks

There are a lot of changes including removing some dependencies and adding some new ones as well as changing how we enrol in courses entirely. 
Any dependency updates are covered in requirements.txt and pyproject.toml

**Comment by sidhant-khamankar** [comment]
Not working alpha branch @cullzie 

Not enough time to solve captcha

These are the errors

DevTools listening on ws://127.0.0.1:14636/devtools/browser/97d25227-fd2a-4b6d-8965-fbbef482e0bc
[22588:5528:0213/154241.534:ERROR:device_event_log_impl.cc(211)] [15:42:41.535] USB: usb_device_handle_win.cc:1049 Failed to read descriptor from node connection: A device attached to the system is not functioning. (0x1F)
[22588:5528:0213/154241.535:ERROR:device_event_log_impl.cc(211)] [15:42:41.535] USB: usb_device_handle_win.cc:1049 Failed to read descriptor from node connection: A device attached to the system is not functioning. (0x1F)
Udemy user failed to login
Closing browser

**Comment by cullzie** [comment]
@sidhant-khamankar The captcha won't show at all anymore so there should be no need to solve captcha. As for the error linked please provide some more info on your system please. The error shown seems to be related to a usb device connected to your system. I'll add more logs on Alpha now to help identify the login failure.

**Comment by sidhant-khamankar** [comment]
@cullzie I have wireless mouse's USB connected. 
System Info: Windows 10 Home 1909, Intel i5 10300H, Nvidia Geforce 1650Ti, 8GB Ram

**Comment by cullzie** [comment]
I've pushed some more updates to Alpha. There should be more logging now. If running could you please do so with `--debug` flag. It will help debug any issues which might arise. Thanks

**Comment by sidhant-khamankar** [comment]
Tried new patch and  same error occurs and still captcha is coming.


DevTools listening on ws://127.0.0.1:3537/devtools/browser/50145672-c054-4116-8da0-23f4365b7b02
[2192:16260:0213/182352.211:ERROR:device_event_log_impl.cc(211)] [18:23:52.211] USB: usb_device_handle_win.cc:1049 Failed to read descriptor from node connection: A device attached to the system is not functioning. (0x1F)
Udemy user failed to login
Closing browser

**Comment by anevskistefan** [comment]
Does this works only for Firefox? Because i've tried on Chrome and it give me the captcha too and closes the window

**Comment by fakeid30** [comment]
@anevskistefan use the alpha branch.

**Comment by cullzie** [comment]
Ah yes the one installed from pypi is not updated. Which is called like `udemy_enroller --debug` 
To run the one from the alpha branch you need to run `udemy_enroller.py`
Glad to hear it's working for someone else 🙂

**Comment by cullzie** [comment]
@sidhant-khamankar To go through the issues you mentioned the malformed URL is a normal issue with some links from tutorialbar in bit.ly format. We can probably just drop them in the scraping phase now though.

The issue with throttling is to do with enrolling too quickly. We'll just need to retry in these cases. Even with throttling it should be a lot quicker than using the browser 🙂

The issue with 0 links on discudemy is because it offers free courses as well which we are not interested in.

**Comment by anevskistefan** [comment]
@cullzie in the readme file says that my settings are saved in /home/username/.udemy_enroller on linux, but when i go there i can not find that folder

**Comment by anevskistefan** [comment]
I tried now with the command python3 udemy_enroller.py --browser firefox --max-pages 500 --debug and this is what i got

![Screenshot_2021-02-13_16-24-02](https://user-images.githubusercontent.com/78988919/107853873-f3c66e80-6ddd-11eb-9ac0-872bfd9f175b.png)

**Comment by cullzie** [comment]
@anevskistefan it looks like you are not running on the `alpha` branch

**Comment by anevskistefan** [comment]
@cullzie i need to run it like "udemy_enroller.py --browser firefox --max-pages 500? Sorry for misunderstanding, i'm new in this :))

**Comment by cullzie** [comment]
@anevskistefan if you are on the `alpha` branch you can run it like `udemy_enroller.py --debug` 
There is no need to specify a browser anymore as it is no longer used.
Just make sure you have installed the new requirements listed in `requirements.txt` file: `pip install -r requirements.txt`

**Comment by anevskistefan** [comment]
@cullzie I managed to do that man, thank you a lot. It works just fine!

**Comment by anevskistefan** [comment]
@cullzie Man i started the program and on the 30page it shows me this.
![Screenshot_2021-02-14_00-54-38](https://user-images.githubusercontent.com/78988919/107865519-4dbb4880-6e5f-11eb-8d3e-c309d23de799.png)

**Comment by harmitstar** [comment]
Can we have cookie based login, i.e. add cookies values from already logged in session

**Comment by fakeid30** [comment]
> Same problem here

@biswajit1602 Saying same problem here in comment is unhelpful. Use the emoji. This is not social media. 



> @cullzie Man i started the program and on the 30page it shows me this.
> ![Screenshot_2021-02-14_00-54-38](https://user-images.githubusercontent.com/78988919/107865519-4dbb4880-6e5f-11eb-8d3e-c309d23de799.png)

@anevskistefan please use another discussion thread to discuss your issue, do not meander this issue. As seen in https://github.com/aapatre/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE/discussions/236, you tend to jump into random things despite not knowing github workflow. Please educate yourself first, when you comment trivial shits on an issue created for something else, everyone gets an email and it's super annoying because when I get an email for an issue that's breaking functionality, I expect to see something regarding that functionality, not trivial how to post. So please, do not annoy the developers/maintainers. 

> Can we have cookie based login, i.e. add cookies values from already logged in session

@harmitstar open a new issue, but before that, check the alpha version. We are going through a transition period, we advice you to please be patient with feature request.

**Comment by MesterPerfect** [comment]
I have the same problem on all of my browsers 
 - OS: Windows8.1 x64
 - Browser chrome, Edge, Firefox.

**Comment by xoco70** [comment]
In my case, it won't work neither, but with slightly different case. It keeps asking for captcha, I solve it manually, but it never accept it. I did it many times so I double checked there is no error in when I solve it. I can't go further captcha, even manually. And yes, I am talking about Udemy Capcha, the google Captcha is not an issue.

**Comment by fakeid30** [comment]
@MesterPerfect @xoco70  You need to use the alpha branch

**Comment by xoco70** [comment]
@fakeid30 Ah OK, after installing new requirements and deleting the --browser=chrome, it seems to be working without a browser. Good improvement !

**Comment by vincekirkov** [comment]
Tried out the alpha branch. I am getting "Checkout failed" errors for all courses with two different users. Any idea?
```
Checkout failed: https://www.udemy.com/course/onboarding-employees-learning-development-strategies/
Checkout payload: {'checkout_event': 'Submit', 'shopping_cart': {'items': [{'discountInfo': {'code': 'A2A9A6CE07F81CD1AC7C'}, 'purchasePrice': {'amount': 0, 'currency': 'EUR', 'price_string': 'Free', 'currency_symbol': '€'}, 'buyableType': 'course', 'buyableId': 3811080, 'buyableContext': {}}], 'is_cart': True}, 'payment_info': {'payment_vendor': 'Free', 'payment_method': 'free-method'}}
In cache: https://www.udemy.com/course/plc-advance-course-data-registers-and-internal-relays/?couponCode=FEB22021
Checkout failed: https://www.udemy.com/course/pic18-microcontroller-step-by-step-guide/
Checkout payload: {'checkout_event': 'Submit', 'shopping_cart': {'items': [{'discountInfo': {'code': 'FEB22021'}, 'purchasePrice': {'amount': 0, 'currency': 'EUR', 'price_string': 'Free', 'currency_symbol': '€'}, 'buyableType': 'course', 'buyableId': 1975432, 'buyableContext': {}}], 'is_cart': True}, 'payment_info': {'payment_vendor': 'Free', 'payment_method': 'free-method'}}
Checkout failed: https://www.udemy.com/course/the-data-science-course-2020-q2-updated-part-1/
```

**Comment by willbrewster** [comment]
I'm running the alpha branch and getting the following error. Any idea why?

```Loading cookies from file
Loading existing course details
Currently enrolled in 0 courses
tutorialbar scraper is running
discudemy scraper is running
Error in get request: Cannot connect to host www.tutorialbar.com:443 ssl:default [No route to host]
Page: 1 of None scraped from tutorialbar.com
Error while running tutorialbar scrapper: 'NoneType' object is not iterable
Error in get request: Cannot connect to host discudemy.com:443 ssl:default [No route to host]
Error while running discudemy scrapper: 'NoneType' object has no attribute 'decode'```

**Comment by vinhvan99** [comment]
I get the alpha branch and getting getting the following error.
![image](https://user-images.githubusercontent.com/66297651/108144973-42854880-70fd-11eb-903d-fb920f113d1d.png)

**Comment by fakeid30** [comment]
@vincekirkov @willbrewster @vinhvan99 there was a pull request sent last night, please do a git pull on the alpha branch. Then try again, if it does not work, delete the cookie file (.cookie). 

you can find it in the root folder. 

One more thing, alpha branch is not supported for end usage, there has been massive changes to udemy that they implemented to hinder us, so we are trying to fix this and then we will launch it. Any further query for usage support might go unanswered.

**Comment by rashideng** [comment]
I'm getting "Checkout failed:" Error
![Screenshot 2021-02-17 132143](https://user-images.githubusercontent.com/65023570/108172911-71aeb080-7123-11eb-9590-e4eff8c8682e.png)

**Comment by vincekirkov** [comment]
The Checkout errors were solved for me after deleting the .cookie file from .udemy_enroller.
Thanks!

**Comment by lukepes** [comment]
I also keep getting checkout failed errors. Deleting .cookie does not help.

**Comment by vincekirkov** [comment]
> I also keep getting checkout failed errors. Deleting .cookie does not help.

Try registering a new account (or using an account with not too many courses) and delete the cookie again. This solved it for me.

**Comment by lukepes** [comment]
Thanks for help, but now i get another message:

python udemy_enroller.py
Loading existing settings
Loading cookies from file
Exception in redeem courses: 'NoneType' object is not subscriptable

It appeared after deleting cookies. Before I was getting some html code in the console.

**Comment by MesterPerfect** [comment]
Hi, how do I run alpha branch?

**Comment by sidhant-khamankar** [comment]
> Hi, how do I run alpha branch?

Switch to alpha branch and download as zip.
Extract the folder and follow the guidelines in readme.md

**Comment by abdulalief** [comment]
> Hi, how do I run alpha branch?

1. switch repos to branch branch 
`git fetch --all`
`git checkout alpha`

2. install dependency files
`pip install -r requirements.txt`

3. run script
`python udemy_enroller.py`

it should run properly

**Comment by lukepes** [comment]
Still getting the checkout failed errors, even with a brand new account with no courses. Anybody has a fix for that?

**Comment by jiayz1997** [comment]
> > Hi, how do I run alpha branch?
> 
> 1. switch repos to alpha branch
>    `git fetch --all`
>    `git checkout alpha`
> 2. install dependency files
>    `pip install -r requirements.txt`
> 3. run script
>    `python udemy_enroller.py`
> 
> it should run properly

I got error message:  
error: pathspec 'alpha' did not match any files known to git

**Comment by fakeid30** [comment]
What @abdulalief wrote is correct, if you need a more thorough tutorial here's where you can see what exactly is needed and you can follow along if you so choose. But from personal experience, there is no way this should fail. So I will chalk it up to user error. 

https://devconnected.com/how-to-switch-branch-on-git/

@lukepes @jiayz1997

**Comment by fakeid30** [comment]
What @abdulalief wrote is correct, if you need a more thorough tutorial here's where you can see what exactly is needed and you can follow along if you so choose. But from personal experience, there is no way this should fail. So I will chalk it up to user error. 

https://devconnected.com/how-to-switch-branch-on-git/

@lukepes @jiayz1997

**Comment by jiayz1997** [comment]
> What @abdulalief wrote is correct, if you need a more thorough tutorial here's where you can see what exactly is needed and you can follow along if you so choose. But from personal experience, there is no way this should fail. So I will chalk it up to user error.
> 
> https://devconnected.com/how-to-switch-branch-on-git/
> 
> @lukepes @jiayz1997

![image](https://user-images.githubusercontent.com/58965055/109675832-22ff0e80-7b46-11eb-8171-4905db3eb905.png)
Did I did anything wrong? 
I still can not run script without browser.

**Comment by fakeid30** [comment]
@jiayz1997 you are not the target audience for an alpha branch, please wait for the release of stable.

**Comment by fakeid30** [comment]
@cullzie when can we merge alpha to develop and / or develop to stable? Any timeframe?

**Comment by cullzie** [comment]
@fakeid30 We can probably merge now. It works to some degree which is much better than the current develop branch. I haven't seen any huge bugs just different users having different issues. Would be easier if they were in separate bugs instead of under this megathread 😄

**Comment by cullzie** [comment]
@fakeid For stable it's the same story as above really. Getting this to master is better than what is currently there

**Comment by fakeid30** [comment]
@cullzie Yes that's what I thought. Let's cut a release and rebase alpha to develop and delete alpha? 

I'm tired of random issue under this megathread. It's becoming a maintenance nightmare.

**Comment by cullzie** [comment]
@fakeid30 That sounds good to me. Ye I find it hard to understand what the problems actually are under this thread. Closing it and allowing people to create standalone bugs will help everyone
