### ISSUE TITLE
[BUG]cannot login on Udemy 

### ISSUE THREAD

**Issue by MesterPerfect** [aapatre/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE#243]
Hi
I cannot log in using the program to the Udemy website 
I use this command in the command prompt 
`udemy_enroller --browser=chrome`
After typing the code at the command prompt, the browser opens and tries to log in, but an error occurs and the connection is closed quickly 

 - OS: Windows8.1 x64
 - Browser chrome, Edge, Firefox.

This is a review of the problem 
https://u.pcloud.link/publink/show?code=XZ9OpSXZ1YFFVOlhui7Jr24oL45Fr8Nf2U2X

**Comment by fakeid30** [comment]
this is a known issue and being discussed here https://github.com/aapatre/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE/issues/233

there is a patch that fixes this, the patch is on alpha stage https://github.com/aapatre/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE/pull/242
