### ISSUE TITLE
[BUG]Unable to fetch existing courses. Login was not successful

### ISSUE THREAD

**Issue by xoco70** [aapatre/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE#244]
I am on the alpha branch. Yesturday, I could make it work.

Today, after launching it with:

```
python3 udemy_enroller.py

➜  Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE git:(alpha) ✗ python3 udemy_enroller.py
Loading existing settings
Loaded cookies from file
Loading existing course details
Unable to fetch existing courses. Login was not successful
```

I tried to log in manually with my user / pass and I can do it successfully.

is there a debug mode? What should I do ?

**Comment by fakeid30** [comment]
Run it with --debug

**Comment by yaasin12** [comment]
C:\Users\Yaas\Desktop\ud1>py ud.py --debug
Enabled debug logging
Loading existing settings
Loaded cookies from file
Loading existing course details
Unable to fetch existing courses. Login was not successful
Exception in redeem courses: 'results'

**Comment by cullzie** [comment]
Ye we need to implement a retry if the cookies have expired. 
You can remove them manually from your home directory for now. Just delete the `.cookie` file

**Comment by xoco70** [comment]
yep, found it here : rm ~/.udemy_enroller/.cookie, now working
