### ISSUE TITLE
[BUG]Unexpected exception: Malformed url passed

### ISSUE THREAD

**Issue by abdulalief** [aapatre/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE#251]
**Describe the bug**
Unexpected exception: Malformed url passed in: https://www.udemy.com/course/the-complete-ios-10-developer-course/

**To Reproduce**
run the program as usual 
`python udemy_enroller.py` 
occasionally the error will occur on some of the links

**Expected behavior**
should be auto enroll

**Screenshots**
![bug malformed url passed](https://user-images.githubusercontent.com/5622239/109451323-c46f5d00-7a7f-11eb-8983-6b423579b715.jpg)

**Desktop (please complete the following information):**
- Windows 10
- python 3.9.1

**Additional context**
it looks like the bug appear when the course being open, are free courses on udemy
should be auto enroll too.

**Comment by cullzie** [comment]
@abdulalief These Urls do not contain a discountCode hence we are raising an error that they are malformed. 
These courses are usually is FREE and the enroller currently only supports enrolling in paid courses which have a discount code to bring the price to Zero.

**Comment by fakeid30** [comment]
@cullzie i think there is a scope to graciously handle this with better try catch block.

**Comment by cullzie** [comment]
@fakeid30 Ye it can be removed entirely. 
We can send it to a debug log since most people don't care about this happening or want to see it happening
