### ISSUE TITLE
[FEATURE REQUEST] deployable on heroku free dyno or repl.it or vercel or any where can use it free & non stop scrape coursed without need personal device

### ISSUE THREAD

**Issue by kakamband** [aapatre/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE#258]
**Is your feature request related to a problem?** Yes , for auto enrolled succeed but I'm always must be run it on my personal pc or mobile termux with so much processing percent.

**Describe the solution you'd like**
please  make it deployable on heroku free dyno or repl.it or vercel or any where can use it free & non-stop scrape course/s & auto enroll without need personal device allways on requirement.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by fakeid30** [comment]
@kakamband this is prohibited in most ToS.
