### ISSUE TITLE
[FEATURE REQUEST] Remove old caching logic

### ISSUE THREAD

**Issue by cullzie** [aapatre/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE#259]
**Is your feature request related to a problem? Please describe.**
We can remove the old way of caching now (caching to file) as we are able to get the courses we are currently enrolled in directly from udemy. This means we can quickly check if the course id we have is one we have already enrolled in

**Describe the solution you'd like**
Update udemy.py to have a list of the course_ids we are currently enrolled in. Then we can simply check if we are already enrolled. On successful enrolment we can add the newly enrolled course_id to this list

**Describe alternatives you've considered**
We could leave in the old cache but it is not necessary and consumes disk space

**Additional context**

**Comment by fakeid30** [comment]
Good idea.
