### ISSUE TITLE
[BUG] Checkout doesn't return a valid json .

### ISSUE THREAD

**Issue by iaman1998** [aapatre/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE#267]
**Describe the bug**
When running the script I am getting this error. 
Unexpected exception: Checkout failed: Code: 400 Text: {"checkout_environment":["This field is required."]}

**To Reproduce**
Steps to reproduce the behaviour:
Running the script normally produces this behaviour.

**Screenshots**
<img width="565" alt="Screenshot 2021-04-04 at 1 24 32 PM" src="https://user-images.githubusercontent.com/54236450/113502299-1b69c580-9549-11eb-9324-f73c7c41c96c.png">

**Desktop (please complete the following information):**
 - OS: MacOs 10.15.2
 - Browser Safari
 - Version 13.0.4

**Comment by fakeid30** [comment]
@iaman1998 there is a fix for this on the develop branch, please switch to that. 

@cullzie shall we merge the pending PR and cut a new release?

**Comment by cullzie** [comment]
> @iaman1998 there is a fix for this on the develop branch, please switch to that. 
> 
> @cullzie shall we merge the pending PR and cut a new release?

Ye sure. It will be tonight/tomorrow before I have time to release to pypi but we can merge it to master now 👍

**Comment by fakeid30** [comment]
Think we need a formal review since it's a contribution from a first time contributor.

**Comment by cullzie** [comment]
> Think we need a formal review since it's a contribution from a first time contributor. 
Ah ok. Sorry I misread the message. I should have time a look at it tomorrow 👍

**Comment by iaman1998** [comment]
Hey , sorry to budge in the conversation , but is there any tutorial of sorts where i can learn about these udemy apis and how to use it to automate course enrolling?

**Comment by cullzie** [comment]
@iaman1998 We have just reverse engineered how it was done. I'd say to have a look at the codebase to get an idea of what we are doing. In particular this file: https://github.com/aapatre/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE/blob/master/udemy_enroller/udemy.py
