### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by vvvlad** [aapatre/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE#269]
**Describe the bug**
Not enrolling. 
On enroll request call:
checkout_result = self.session.post(self.CHECKOUT_URL, json=payload)
Returns 400 and checkout_result.text is:
'{"checkout_environment":["This field is required."]}'

**To Reproduce**
Regular run of the package

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Version [master]

**Comment by fakeid30** [comment]
Use the develop branch.

**Comment by cullzie** [comment]
@vvvlad  Fix should be available on master or via PyPi now
