### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Abdo-human** [aapatre/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE#270]
Hi guys. From a while when I run the code of udemy_enroller.py I got this error or glitch : 

Got 12 links from https://www.tutorialbar.com in 6.96 seconds
Unexpected exception: 'NoneType' object has no attribute 'group'
Unexpected exception: 'NoneType' object has no attribute 'group'
Unexpected exception: 'NoneType' object has no attribute 'group'
Unexpected exception: 'NoneType' object has no attribute 'group'

and so on that no courses are been enrolled to my account.

Any solutions?

**Comment by fakeid30** [comment]
@Abdo-human use the develop branch

**Comment by Abdo-human** [comment]
> @Abdo-human use the develop branch

how?

**Comment by Abdo-human** [comment]
> @Abdo-human use the develop branch

what?
how?

**Comment by Destroy666x** [comment]
@Abdo-human git checkout develop locally and run udemy_enroller file from that

**Comment by cullzie** [comment]
@Abdo-human Fix should be available on master or via PyPi now
