### ISSUE TITLE
[BUG] Error while running coursevania scraper: 'int' object has no attribute 'get'

### ISSUE THREAD

**Issue by manafn** [aapatre/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE#271]
```
Loading existing settings
Loading cookies from file
Loading existing course details
Currently enrolled in 2682 courses
tutorialbar scraper is running
discudemy scraper is running
coursevania scraper is running
Error while running coursevania scraper: 'int' object has no attribute 'get'
Page: 1 of 842 scraped from tutorialbar.com
```

**Comment by klamar** [comment]
The URL https://coursevania.com/wp-admin/admin-ajax.php?... returns now a 403 Forbidden, thus the get() method in udemy_enroller/http.py returns -1 instead of the response text

**Comment by klamar** [comment]
@manafn I think the issue is still open, I just wanted to give some context for a developer who wants to address this issue.

**Comment by manafn** [comment]
Oh, I thought the problem is with the number of courses only and not affecting the scripts work and that is because of the source cursevania so there is nothing to do about

**Comment by D-SAMPATH** [comment]
Its Showing That error 'non type' object has no attribution 'find' can you give me a solution and tell me the process how to do it

**Comment by cullzie** [comment]
Thanks for reporting I will have a look at this
