### ISSUE TITLE
Script not working

### ISSUE THREAD

**Issue by ZorinArch** [aapatre/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE#279]
script not working

`$ python udemy_enroller`
```
Loading existing settings
Loading cookies from file
Caching cookies for future use
Loading existing course details
Retrying login
Deleting cookies
Loading cookies from file
Exception in redeem courses: 'NoneType' object is not subscriptable
```
OS: Arch Linux
i use latest version 3.1.0

Also, how i can choose browser?

**Comment by cullzie** [comment]
Hey @ZorinArch,
 Can you run with `python udemy_enroller --debug` and post those logs please.

Browser support has been dropped. We no longer use the browser in order to enrol

**Comment by ZorinArch** [comment]
Hi @cullzie ,
Thank you for your respond. i did not change anything, but the script working now.  enroll courses without browser is good.

**Comment by cullzie** [comment]
Thanks for the update @ZorinArch 
Might have been a connection issue if that's the case. 

Going to close this ticket until we see it again :eyes:
