### ISSUE TITLE
[FEATURE REQUEST] Update the video on the repo to represent the current version

### ISSUE THREAD

**Issue by cullzie** [aapatre/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE#280]
**Is your feature request related to a problem? Please describe.**
Not a huge problem. Just if new users want to see the script the video still shows browser usage and old CLI arguments which might be confusing

**Describe the solution you'd like**
An updated video hosted wherever. Link needs to be updated in the `README.md`

**Additional context**
I think its sufficiently out of date to warrant an update at this point

**Comment by fakeid30** [comment]
Good idea, I agree
