### ISSUE TITLE
[QUESTION] 

### ISSUE THREAD

**Issue by xasharma32** [aapatre/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE#287]
Type out your question here. Please make sure that this is a topic that isn't already covered in the README.
Bro how to re-enter a new id and password ... please update the readme file?

**Comment by xasharma32** [comment]
Bro i have tried it but it using the previous account cookies

**Comment by cullzie** [comment]
Ah ok you'll have to manually delete the `.cookie` file from your home directory in that case. This is the same directory the settings.yaml is stored in. It should show in the terminal where that's saved after going through the setup steps

We can add a delete-cookie arg to the cli as well for this in future

**Comment by xasharma32** [comment]
Thank you bro for your amazing efforts
