### ISSUE TITLE
Fix firefox webdriver autoinstall

### ISSUE THREAD

**Issue by fakeid30** [aapatre/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE#29]
The current implementation lacks geckodriver autoinstall, we need to figure out a way to autoinstall geckodriver so that we don't have to manually install it and get parity with chrome and edge.

**Comment by cullzie** [comment]
Hey @fakeid30,

Can there be more information added on this please? Like is it a specific OS that this issue is experienced on?

If I revert back to this commit with the GeckoDriver install it works fine:
[Removing GeckoDriver install](https://github.com/aapatre/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE/commit/abb1d837458d50f73d6b2ce66229e6f7b94f88c3
)

I'm running Ubuntu 20.04.1 LTS

**Comment by fakeid30** [comment]
> Hey @fakeid30,
> 
> Can there be more information added on this please? Like is it a specific OS that this issue is experienced on?
> 
> If I revert back to this commit with the GeckoDriver install it works fine:
> [Removing GeckoDriver install](https://github.com/aapatre/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE/commit/abb1d837458d50f73d6b2ce66229e6f7b94f88c3)
> 
> I'm running Ubuntu 20.04.1 LTS

with this commit it does not work on arch linux and firefox installed from arch repo

**Comment by fakeid30** [comment]
@cullzie what we can do is , have 2 version of this line which queries the linux version , if it runs arch linux we run  `driver = webdriver.Firefox()` if it is any other linux / windows / mac os we run  `driver = webdriver.Firefox(executable_path=GeckoDriverManager().install())` but i cant test since i dont have access to a windows machine.

**Comment by cullzie** [comment]
@fakeid30 thanks for the info. What version of Firefox are you running? 
Ye that solution is something that's workable

**Comment by fakeid30** [comment]
> @fakeid30 thanks for the info. What version of Firefox are you running?
> Ye that solution is something that's workable

81.0.2

**Comment by cullzie** [comment]
So the only solution that works for you at the moment is to manually specify the driver path? 

Unfortunately it will require some input in that case unless the user sets an environment variable up front which would mean only configuring it once. 
Another option is to prompt the user on first run and store in a driver_config file if the automatic install fails.

I don't think it will ever be possible to support every variation on every OS though. I'd add to the FAQ/README that anything that is not a vanilla OS are edge cases and not tested fully so `Here be dragons` :imp:

**Comment by fakeid30** [comment]
> I don't think it will ever be possible to support every variation on every OS though. I'd add to the FAQ/README that anything that is not a vanilla OS are edge cases and not tested fully so `Here be dragons` imp

Actually yeah, if someone is competent enough to use a custom kernel, they should be competent enough to fix the script, or they can ask help in issue , we can add to README that custom kernels are not supported and run 2 variation of this code. 

If I knew zen kernel on ubuntu does not work as well we could do something like `if kernel==*****arch || *****zen` execute first line. The **** has to be done with regex. 

But I am not sure if zen kernel in ubuntu fails as well, can you try testing this scene? https://liquorix.net zen kernel for ubuntu is here.

**Comment by cullzie** [comment]
Ye there's no problem with people asking for help with specific issues they might be experiencing but it's impossible to code for every possible situation. Unless you want spaghetti code :smile: 

I agree that if someone is using a custom kernal or anything not vanilla they already have some tech know how and would just need some guidance on fixing their issue locally
