### ISSUE TITLE
[BUG]: Disable Comidoc (DEV Bug)

### ISSUE THREAD

**Issue by jlarini** [aapatre/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE#291]
**Describe the bug**
Hi, is there a bug on my pull, sorry...

To solve, change line 47 of cli.py

**From:** coursevania_enabled = True, **_True_**, True, True, True
**To:** coursevania_enabled = True, **_False_**, True, True, True

the second "True" is for "comidoc" and I don't finished it yet.

**Comment by cullzie** [comment]
@jlarini I think you can remove comidoc completely if its not working.

Was it working for you?

**Comment by jlarini** [comment]
No, It´s returning 0 courses...
But I'll try to correct it until tomorrow...
It's the first time I contribute... So I made this mistake...

**Comment by cullzie** [comment]
@jlarini That's no problem. Take your time. We all learn from our mistakes :smile:

**Comment by jlarini** [comment]
corrected!
