### ISSUE TITLE
[BUG] `Enroll now` button not clicked.

### ISSUE THREAD

**Issue by vvvlad** [aapatre/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE#293]
**Describe the bug**
`Enroll now` button not clicked.

**To Reproduce**
1. Both master and develop branches
2. Execute:  udemy_enroller --browser google-chrome
3. Installed Chrome version is  90.0.4430.212
4. Browser opened, authentication ok, but never subscribes to courses, because stays on Enroll page for couple of seconds without button click

**Expected behavior**
Clicks on Enroll now button working.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Crome
 - Version: master or develop branches, running from code.

**Comment by fakeid30** [comment]
@vvvlad this is not the way we work anymore. I suggest you do a pull or update your version. it's been a long time since this behavior has been changed. 

closing.

**Comment by vvvlad** [comment]
What is the expected behavior? I get the same on any branch or when work on latest tag v.3.1.0

**Comment by fakeid30** [comment]
@vvvlad please record a screenshot and share.
