### ISSUE TITLE
[BUG] Not able to enter password.

### ISSUE THREAD

**Issue by Raagaception** [aapatre/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE#294]
**Describe the bug**
Can't enter password when asked, the terminal doesn't accept any input.

**To Reproduce**
1. Go to terminal. (VS Code or cmd, any one)
2. Start the script.
3. Works fine till it asks password, after which can't enter it.

**Expected behavior**
It allows me to enter the password.

**Screenshots**
![image](https://user-images.githubusercontent.com/72780589/120059823-87f8d080-c071-11eb-8a14-e13c899abf6b.png)

**Comment by fakeid30** [comment]
@Raagaception this is intended behavior to protect someone from seeing you enter your password. If you enter the password and press enter this will work. 

@cullzie can we add a note on the string saying password field will appear empty but it is indeed working? Or mask the password input?

**Comment by Raagaception** [comment]
AHA! Got it, thanks.
