### ISSUE TITLE
[BUG]: tutorialbar scraper utf-8 codec can't decode byte 0x80 in position 1154: invalid start byte

### ISSUE THREAD

**Issue by k3rm3h3k34r** [aapatre/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE#296]
**Describe the bug**
This bug in tutorialbar scraper has appeared recently

**To Reproduce**
1. install and run udemy_enroller
2. Error - "Error while running tutorialbar scraper: 'utf-8' codec can't decode byte 0x80 in position 1154: invalid start byte"
3. See error

Errors from app.log ($ cat app.log | grep Error) [run this command in terminal in .udemy_enroller directory]
2021-05-17 15:06:35,751 - udemy_enroller - ERROR - base_scraper : Error while running coursevania scraper: Expecting value: line 1 column 1 (char 0)
2021-06-09 21:29:13,165 - udemy_enroller - ERROR - base_scraper : Error while running tutorialbar scraper: 'utf-8' codec can't decode byte 0x80 in position 1154: invalid start byte
2021-06-09 21:58:36,463 - udemy_enroller - ERROR - base_scraper : Error while running tutorialbar scraper: 'utf-8' codec can't decode byte 0x80 in position 1154: invalid start byte

settings.yaml
udemy:
  categories: [Development, Design, Business, Finance, Accounting, IT, Software, Office
      Productivity, Personal Development, Marketing, Lifestyle, Photography, Video,
    Health, Fitness, Music, Teaching, Academics, Finance & Accounting, IT & Software,
    Photography & Video, Health & Fitness, Teaching & Academics]
  email: email123@gmail.com
  languages: [English, German, Turkish, Arabic, Hebrew, Chinese, Japanese, French,
    Italian]
  password: password123
  zipcode: '123456'

**Expected behavior**
The tutorialbar scrapper does not run, but other scrappers work fine.

**Desktop (please complete the following information):**
 - OS: [Kali Linux]
 - Kernel: Linux 5.10.0-kali7-amd64
 -Python Version [3.9.2]

**Comment by fakeid30** [comment]
@k3rm3h3k34r thanks for the detailed bug report. Appreciate it.

**Comment by cullzie** [comment]
@k3rm3h3k34r Sorry I am only having a proper look at this now. I can't seem to reproduce the issue at the moment. I will keep an eye out for it. If there is any other info you think might help find the issue please let us know

**Comment by k3rm3h3k34r** [comment]
The issue seems to be in between the web request and python processing the encoding, seems to be gone. Recently, I haven't seen this issue, maybe it resolved.
Now the issue (**UPDATE**): 
1. Error in get request: Cannot connect to host www.tutorialbar.com:443 ssl:True [SSLCertVerificationError: (1, "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'www.tutorialbar.com'. (_ssl.c:1123)")]
2. Error while running tutorialbar scraper: 'NoneType' object has no attribute 'find_previous_sibling'
3. Error while running tutorialbar scraper: 'NoneType' object has no attribute 'find'

For errors listed in app.log check this paste:
https://pastebin.com/v9VaZP5c

Steps to reproduce the behavior:
1. run udemy_enroller

**Comment by cullzie** [comment]
Closing as it doesn't appear to be reproducible.
