### ISSUE TITLE
[BUG] Can't install on Mac OS X Big Sur

### ISSUE THREAD

**Issue by DarkSkull91** [aapatre/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE#299]
**Describe the bug**
I'm trying to install udemy_enroller but I always get this error:
```
Traceback (most recent call last):
  File "/Users/a465196/opt/anaconda3/bin/udemy_enroller", line 5, in <module>
    from udemy_enroller.cli import main
  File "/Users/a465196/opt/anaconda3/lib/python3.8/site-packages/udemy_enroller/__init__.py", line 3, in <module>
    from .settings import Settings
  File "/Users/a465196/opt/anaconda3/lib/python3.8/site-packages/udemy_enroller/settings.py", line 6, in <module>
    from ruamel.yaml import YAML, dump
ModuleNotFoundError: No module named 'ruamel
```

**To Reproduce**
1. Go to Terminal
2. Run command pip install udemy-enroller
3. Get the error

**Expected behavior**
Script run smoothly like in Linux.

**Desktop (please complete the following information):**
 - OS: Mac OS X Big Sur
 - Python 3.8.5

**Comment by fakeid30** [comment]
@DarkSkull91 install via pip or do pip install -r requirements.txt 

read the readme

**Comment by DarkSkull91** [comment]
I get the same error.

**Comment by fakeid30** [comment]
that is impossible. record a screencast and share.

**Comment by DarkSkull91** [comment]
Here it is https://streamable.com/nh1jqr

**Comment by DarkSkull91** [comment]
Here it is https://streamable.com/sfpq2j

**Comment by DarkSkull91** [comment]
So, do you know how I can resolve?

**Comment by fakeid30** [comment]
@DarkSkull91 

`pip install udemy_enroller`

then run 

`udemy_enroller`

I think the reason you are facing this issue is a path mismatch or something of that nature. I can not reproduce this.
