### ISSUE TITLE
[FEATURE REQUEST] New site to scrape

### ISSUE THREAD

**Issue by GodlyHockey** [aapatre/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE#302]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Add https://comidoc.net/coupons 

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by fakeid30** [comment]
@GodlyHockey we had this before, they keep changing their API and it's not feasible to play a cat and mouse game with them anymore.
