### ISSUE TITLE
[FEATURE REQUEST] Generate a report on each run on enrolled courses

### ISSUE THREAD

**Issue by owlg** [aapatre/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE#304]
**Is your feature request related to a problem? Please describe.**
It can be difficult for the user to know which courses he/she is enrolled in (there is so many a day). Sometimes, the user receives emails when being enrolled in the course, but they are often deleted. 

**Describe the solution you'd like**
Generate a report, if the user wishes, on a given run. The report can be a HTML file (have links to the enrolled courses)/txt file showing what the user has been enrolled in (they can be stored in the same folder /reports/)

**Describe alternatives you've considered**
Copy and pasting outputs everytime after each run

**Comment by fakeid30** [comment]
@owlg this is on the dev branch, it'll be pushed to main soon.
