### ISSUE TITLE
[FEATURE REQUEST] Studybullet thirdparty website for udemy coupons

### ISSUE THREAD

**Issue by ninjatall12** [aapatre/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE#310]
**Is your feature request related to a problem? Please describe.**
Help on importing third party websites

**Describe the solution you'd like**
Help on creating a udemy course scraper for a site called study bullet I'm pretty sure the studybullet.py is broken so I need help with that I only have experience using standard python and no experience with the beautiful soup I've already put the add URLs n stuff I get .find_previous_sibling() error I looked at youtube videos for beautiful soup but they seem only for searching for 1 item not several items on a page. the site is fairly simple
![image](https://user-images.githubusercontent.com/58861295/130999058-0c23a086-74fb-4f42-ab8d-18333298b394.png)
![image](https://user-images.githubusercontent.com/58861295/130999141-3ef5419f-8187-40d7-b762-53cf5dd1a809.png)
when you hover over the red button so it gives a link and no short links you need to go through. hope this helped.

**Describe alternatives you've considered**
Manually enrolling in the course

**Additional context**
https://github.com/ninjatall12/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE

**Comment by fakeid30** [comment]
@cullzie thoughts on this?

**Comment by ninjatall12** [comment]
i can't manage to fix the find_all thing idk if its because something to do with page loading n stuff

**Comment by cullzie** [comment]
@ninjatall12 You should be able to access the links on these pages and avoid the date formatting
The pages are ordered most recent to oldest.
**https://studybullet.com/page/1/** 
**https://studybullet.com/page/2/**

I'll have a look at the branch you have on your repo and see about sorting any issues you have there regarding getting the links

**Comment by ninjatall12** [comment]
help no longer needed
