### ISSUE TITLE
if I had a new scraper, how to remake a exe 

### ISSUE THREAD

**Issue by LemoJa** [aapatre/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE#311]
I use pip get this proj and get a udemy_enroller.exe, this is convenient. and if I make another scraper, how to remake a new exe file? I try to use pyinstaller -F -w udemy_enroller.py, but the build exe not running success.

**Comment by fakeid30** [comment]
@LemoJa this is not supported and we don't encourage you to do this. The official and preferred way is to contribute code back to us and then everyone else can benefit. 

Every scrapper has different div element that needs to be scanned. This program is not a general scrapping framework. 

Closing this issue.
