### ISSUE TITLE
[BUG] Unable to enroll in any course

### ISSUE THREAD

**Issue by parasguglani1** [aapatre/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE#312]
**Describe the bug**
logged in successfully, fetching links, skipping non-category courses as well as already enrolled course but Not enrolling in any new one displaying error in debug.
**To Reproduce**
  1. execute udemy_controller --debug
  2. scroll till logging error
 
**Expected behavior**
must enroll instead of giving this error

**Screenshots**
fetching links - 
![image](https://user-images.githubusercontent.com/73358562/131345409-67ea3198-7aec-4db3-ad06-abc0b11c8504.png)

getting same error when it starts to enroll any course
![image](https://user-images.githubusercontent.com/73358562/131345503-04f842d1-fca8-4be1-9978-98c5fff68ccb.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Microsoft Edge Version 92.0.902.84 (Official build) (64-bit)
 - Version:  release V 3.1.0

**Additional context**
I installed the latest version of python and visual studio build tools for C/C++ today to install files from requirements.txt using pip install. first time using this repo with new udemy account.

**Comment by fakeid30** [comment]
this is a known bug affecting indian users. use vpn to change your country.

**Comment by parasguglani1** [comment]
Used Proton VPN and same command and got this error
![image](https://user-images.githubusercontent.com/73358562/131350778-d2851cc8-a53f-4476-a89c-99a02079fbcf.png)

**Comment by fakeid30** [comment]
did you change your udemy location?

**Comment by parasguglani1** [comment]
NO, I have to change Zipcode in settings.yaml or there is any option on udemy site?

**Comment by fakeid30** [comment]
figure it out
