### ISSUE TITLE
[BUG]: Incorrect video replaced in README file

### ISSUE THREAD

**Issue by cullzie** [aapatre/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE#320]
**Describe the bug**
Incorrect video in README was replaced

Should have been the `Video Proof:` video that was changed not the `Davidd Sargent` video even though that is also a bit out of date now

**To Reproduce**
1. View the README

**Expected behavior**
We should revert to the David Sargent video link and update the other link to show the install steps

**Comment by fakeid30** [comment]
Or we can remove the video proof and keep the instruction bit. 

Reverting is an idea I dont hate either.

**Comment by cullzie** [comment]
Ye revert was probably the wrong word to use. We just need to put in the appropriate videos. Probably only the installation one is not outdated at this point
