### ISSUE TITLE
[QUESTION] I guess i got banned?

### ISSUE THREAD

**Issue by mejsler** [aapatre/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE#321]
Loading existing settings
Loading cookies from file
Loading existing course details
HTTP error while trying to fetch Udemy information
404 Client Error: Not Found for url: https://www.udemy.com/api-2.0/users/me/subscribed-courses/?ordering=-last_accessed&fields%5Bcourse%5D=@min,enrollment_time,published_title,&fields%5Buser%5D=@min&page=2&page_size=100
Unable to fetch existing courses. Login was not successful
Exception in redeem courses: 404 Client Error: Not Found for url: https://www.udemy.com/api-2.0/users/me/subscribed-courses/?ordering=-last_accessed&fields%5Bcourse%5D=@min,enrollment_time,published_title,&fields%5Buser%5D=@min&page=2&page_size=100

**Comment by mejsler** [comment]
why i think so (mb I'm wrong)
1) No similar issues
2) Scraping is against TOS
3) Enrolled in 100 courses in short period of time (which is probably easy to detect)

**Comment by jlarini** [comment]
Hi! 
There´s a lot of similar issues...
Udemy changed something...

**Comment by fakeid30** [comment]
@mejsler can you login normally?

**Comment by mejsler** [comment]
> @mejsler can you login normally?

you mean using browser? yes

**Comment by mejsler** [comment]
> There´s a lot of similar issues...
not with this particular error

**Comment by fakeid30** [comment]
> > @mejsler can you login normally?
> 
> you mean using browser? yes

then you are not banned, keep trying, make sure you are updated. This is a non issue as of now, since I can't reproduce it locally.

**Comment by jlarini** [comment]
Sorry... My fault...
The issues was about getting  already enroled courses, login was successfull before it...

**Comment by theqkash** [comment]
Same issue on my side. After 24hrs still not able to use it.

**Comment by jlarini** [comment]
HI, There!

I just executed, about 5 mins ago...
It´s working perfectly.

Sometimes the captcha error occurs, but just run it again, and again... And it works...

**Comment by mejsler** [comment]
Yea yo

> 
> 
> Same issue on my side. After 24hrs still not able to use it.

yea it will work eventually just keep trying from time to time

**Comment by KarolDaniluk** [comment]
I have tried it for 6 days, at least twice a day, every time 5-6 times in a row and it is NOT working.
Every time I get this error:
`404 Client Error: Not Found for url: https://www.udemy.com/api-2.0/users/me/subscribed-courses/?ordering=-last_accessed&fields%5Bcourse%5D=@min,enrollment_time,published_title,&fields%5Buser%5D=@min&page=9&page_size=100
Unable to fetch existing courses. Login was not successful`
If I open this URL in a browser where I am logged into Udemy, I get this error:
`detail : "You do not have permission to perform this action."`
Are you sure they did not change anything on the Udemy side?
BTW my region (postal code) is 82-292 which is Poland.

**Comment by theqkash** [comment]
> BTW my region (postal code) is `80-292` which is Poland.

@KarolDaniluk well, mine is 41-200 so this looks like maybe issue for users from Poland.

**Comment by mejsler** [comment]
last 3 days not working for me as well, same 404 error

**Comment by theqkash** [comment]
@mejsler @KarolDaniluk try to delete .cookie fole from .udemy_enroller directory. Helped for me.

**Comment by mejsler** [comment]
> @mejsler @KarolDaniluk try to delete .cookie fole from .udemy_enroller directory. Helped for me.
tried didn't help

**Comment by KarolDaniluk** [comment]
Deleting user settings and changing postal code give 0 effect.

**Comment by KarolDaniluk** [comment]
I am conveinced that I got secretly 'banned' from enrolling to any new courses.
I found a course with 100% discount code and I couldn't add it to my cart - it was greyed out.
When I log out, added it to the cart, checked out and then log in to my account I got a message:
`We're sorry, but you are not eligible for this discount`
