### ISSUE TITLE
[BUG] Unable to log in since the SSL update, this is 403/404 Client Error

### ISSUE THREAD

**Issue by infantannihilat0r** [aapatre/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE#327]
Since the SLL certificate was changed, I deleted the .cookie file, used --delete-settings, switched from master to develop and whatever I do I am unable to log in. I am on Ubuntu 20.04. 

:~/udemy$ time python3 udemy_enroller.py

Loading existing settings
Loading cookies from file
Loading existing course details
HTTP error while trying to fetch Udemy information
404 Client Error: Not Found for url: https://www.udemy.com/api-2.0/users/me/subscribed-courses/?ordering=-last_accessed&fields%5Bcourse%5D=@min,enrollment_time,published_title,&fields%5Buser%5D=@min&page=59&page_size=100
Unable to fetch existing courses. Login was not successful
Exception in redeem courses: 404 Client Error: Not Found for url: https://www.udemy.com/api-2.0/users/me/subscribed-courses/?ordering=-last_accessed&fields%5Bcourse%5D=@min,enrollment_time,published_title,&fields%5Buser%5D=@min&page=59&page_size=100

real    1m28.161s
user    0m1.128s
sys     0m0.046s

-------------------------------------------------------------------------------------

Using the above links in a browser returns:

{"detail":"You do not have permission to perform this action."}

**Comment by cullzie** [comment]
I am not seeing this error. Is it something that is still happening?

404 means not found. Also I see that the login was not successful on the retry. 
Did you try logging into the browser with the user credentials to see if it is working?

**Comment by theqkash** [comment]
Deleting file .udemy_enroller/.cookie should do the trick.

**Comment by cullzie** [comment]
Ok so it seems like its just a change on their side and the cookie expiring. We can create some steps in FAQ around troubleshooting. 
Deleting cookies should be one of the main checks done before raising a bug report.

**Comment by infantannihilat0r** [comment]
Hi guys, thank you for your replies. As mentioned in the beginning I used --delete-cookies, deleted the .cookie file manually. I installed this on a completely different machine and I am getting the same thing. 

When I log in using a browser, everything seems to be fine, but when I try to paste the URL [https://www.udemy.com/api-2.0/users/me/subscribed-courses/?ordering=-last_accessed&fields%5Bcourse%5D=@min,enrollment_time,published_title,&fields%5Buser%5D=@min&page=59&page_size=100](url) (from the error mentioned in the first post) -  I get this


![image](https://user-images.githubusercontent.com/91798478/135883222-6f21e6dd-f448-4393-a74d-d91c821818c4.png)

**Comment by infantannihilat0r** [comment]
as you can see it is "Caching cookies for future use" after deleting the file:


~/Udemy$ python3 udemy_enroller.py
Loading existing settings
Loading cookies from file
Caching cookies for future use
Loading existing course details
HTTP error while trying to fetch Udemy information
404 Client Error: Not Found for url: https://www.udemy.com/api-2.0/users/me/subscribed-courses/?ordering=-last_accessed&fields%5Bcourse%5D=@min,enrollment_time,published_title,&fields%5Buser%5D=@min&page=89&page_size=100
Unable to fetch existing courses. Login was not successful
Exception in redeem courses: 404 Client Error: Not Found for url: https://www.udemy.com/api-2.0/users/me/subscribed-courses/?ordering=-last_accessed&fields%5Bcourse%5D=@min,enrollment_time,published_title,&fields%5Buser%5D=@min&page=89&page_size=100

**Comment by cullzie** [comment]
Hey @infantannihilat0r I've had a look and the flow is correct just the log is misleading in this case.
The 404 error isn't a result of the code flow. It seems to only be effecting certain users at the moment so its hard to determine exactly what is going on here.

**Comment by infantannihilat0r** [comment]
@cullzie thank you for taking an interest. Script started to work. However, when tried to run this for a family member, it gave 404 again. So... do not run this too often and when you get 404 wait for at least 24hrs? :)

**Comment by cullzie** [comment]
@infantannihilat0r I'm not sure what the cause is yet as I haven't gotten this error. 404 usually means the endpoint doesn't exist. So its weird to see it resolve itself. Possibly udemy are rolling changes to some users. 
We'll know more when it breaks for everyone :laughing:

**Comment by manafn** [comment]
I have this issue too

**Comment by infantannihilat0r** [comment]
Wait for 24 hrs and then try it. Avoid logging in in the meantime.

**Comment by infantannihilat0r** [comment]
@fakeid30 it's working fine for me, I just had to wait. Before I tried to run it every couple of minutes trying to work out why it fails, deleting settings, .cookie file, etc. @manafn reported the same 404 so I recommended leaving Udemy for a day. Regarding VPNs, I am not sure if this will help, YMMV, I tried the USA and Europe (I got company VPN) while I had this temporary ban :)

**Comment by manafn** [comment]
I can't bypass this error tried the solutions above and left it for a day but still the same

**Comment by infantannihilat0r** [comment]
Have you tried VPNs as mentioned by @fakeid30 ? Otherwise not sure what to try next?

**Comment by manafn** [comment]
yes ,I used avaira vpn and warp with no luck 😞

**Comment by infantannihilat0r** [comment]
same here, 403 forbidden

**Comment by cullzie** [comment]
I was able to enroll using selenium again with a workaround added.
I've opened a PR to the alpha branch which can be used for testing going forward.
Currently I can't find a way around the REST enrollment block. Seems to be some CORS policy introduced by Udemy

**Comment by cullzie** [comment]
Discussion link for anyone who gets that far: https://github.com/aapatre/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE/discussions/338

**Comment by cullzie** [comment]
We have released a new version which should be available on pypi now. 
If there are any issues please raise bugs as necessary. Thanks

**Comment by khdan** [comment]
with the latest update it is working :)

**Comment by mejsler** [comment]
not working for me, same error:
Loading existing settings
Loading cookies from file
Loading existing course details
HTTP error while trying to fetch Udemy information
403 Client Error: Forbidden for url: https://www.udemy.com/api-2.0/users/me/subscribed-courses/?ordering=-last_accessed&fields%5Bcourse%5D=@min,enrollment_time,published_title,&fields%5Buser%5D=@min&page=1&page_size=100
Unable to fetch existing courses. Login was not successful
Exception in redeem courses: 403 Client Error: Forbidden for url: ...

**Comment by cullzie** [comment]
@mejsler You are still using the old version. Upgrade with pip `pip install --upgrade udemy_enroller`. It should be on version 4.0.2

**Comment by mejsler** [comment]
@cullzie you're right, my bad. Seems to work now.

**Comment by manafn** [comment]
is it still working on the brower or the api version return to works ?

**Comment by cullzie** [comment]
> is it still working on the brower or the api version return to works ?

Its only working on the browser version. The API version is deprecated and is unusable but still in the code base for now.

**Comment by AirTechWick** [comment]
Got this error after doing:
1. Enabled multi-factor on my account, to test out some stuff
2. Disabled multi-factor
3. Ran Script
4. Error Appeared

Solution:
Deleting the .cookie file worked, and the script was running successfully again

**Comment by Hussnain12** [comment]
> Deleting file .udemy_enroller/.cookie should do the trick.

thanks. it worked
