### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by parasguglani1** [aapatre/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE#355]
**Describe the bug**
unable to upgrade to the latest version of udemy enroller

**To Reproduce**
run pip install --upgrade udemy_enroller
**Expected behavior**
udemy enrolled should be updated

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 -   Gitbash terminal in vs code
 - python version 3.10.0
 - pip version 21.3.1

![Screenshot_240](https://user-images.githubusercontent.com/73358562/142699471-1b73cd5c-9090-451b-a28a-4a24c18e1929.png)

**Comment by cullzie** [comment]
Hey @parasguglani1, Thanks for reporting this.
Could you please copy the full text output into the bug please?
Not really sure what's gone wrong here.

**Comment by parasguglani1** [comment]
> Hey @parasguglani1, Thanks for reporting this. Could you please copy the full text output into the bug please? Not really sure what's gone wrong here.

Requirement already satisfied: h11<1,>=0.9.0 in c:\python310\lib\site-packages (from wsproto>=0.14->trio-websocket~=0.9->selenium->udemy_enroller) (0.12.0)
Using legacy 'setup.py install' for cchardet, since package 'wheel' is not installed.
Installing collected packages: cchardet, brotlipy, aiodns, price-parser, udemy-enroller
    Running setup.py install for cchardet ... error
    ERROR: Command errored out with exit status 1:
     command: 'C:\Python310\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\paras\\AppData\\Local\\Temp\\pip-install-r_npqy5z\\cchardet_00b
82c7ebf314887b05c6219635301cf\\setup.py'"'"'; __file__='"'"'C:\\Users\\paras\\AppData\\Local\\Temp\\pip-install-r_npqy5z\\cchardet_00b82c7ebf314887b05c6219635301cf\\setup.py'"'"';f =
 getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"
', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\paras\AppData\Local\Temp\pip-record-rbu4w196\install-record.txt' --single-version
-externally-managed --compile --install-headers 'C:\Python310\Include\cchardet'
         cwd: C:\Users\paras\AppData\Local\Temp\pip-install-r_npqy5z\cchardet_00b82c7ebf314887b05c6219635301cf\
    Complete output (24 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.10
    creating build\lib.win-amd64-3.10\cchardet
    copying src\cchardet\version.py -> build\lib.win-amd64-3.10\cchardet
    copying src\cchardet\__init__.py -> build\lib.win-amd64-3.10\cchardet
    running build_ext
    building 'cchardet._cchardet' extension
    creating build\temp.win-amd64-3.10
    creating build\temp.win-amd64-3.10\Release
    creating build\temp.win-amd64-3.10\Release\src
    creating build\temp.win-amd64-3.10\Release\src\cchardet
    creating build\temp.win-amd64-3.10\Release\src\ext
    creating build\temp.win-amd64-3.10\Release\src\ext\uchardet
    creating build\temp.win-amd64-3.10\Release\src\ext\uchardet\src
    creating build\temp.win-amd64-3.10\Release\src\ext\uchardet\src\LangModels
    C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Isrc/ext/uchardet/src -IC:\Py
thon310\include -IC:\Python310\Include -IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\include -IC:\Program Files (x86)\Windows Kits\10\inc
lude\10.0.19041.0\ucrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\shared -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um -IC:\Program Files (x86)\
Windows Kits\10\include\10.0.19041.0\winrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\cppwinrt /EHsc /Tpsrc/cchardet\_cchardet.cpp /Fobuild\temp.win-amd64-3.10\Rel
ease\src/cchardet\_cchardet.obj
    _cchardet.cpp
    C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\include\sys/types.h(27): error C2371: '__time32_t': redefinition; different basic types  
    C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt\corecrt.h(593): note: see declaration of '__time32_t'
    C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\include\float.h(38): fatal error C1021: invalid preprocessor command 'include_next'      
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Python310\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\paras\\AppData\\Local\\Temp\\p
ip-install-r_npqy5z\\cchardet_00b82c7ebf314887b05c6219635301cf\\setup.py'"'"'; __file__='"'"'C:\\Users\\paras\\AppData\\Local\\Temp\\pip-install-r_npqy5z\\cchardet_00b82c7ebf314887b0
5c6219635301cf\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code
 = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\paras\AppData\Local\Temp\pip-record-rbu4w196\ins
tall-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Python310\Include\cchardet' Check the logs for full command output.

I can't find logs. can you provide a reference?

**Comment by parasguglani1** [comment]
issue was with installing chhardet I installed with conda using `conda install -c conda-forge cchardet`  and it's working fine now.
