### ISSUE TITLE
[QUESTION] How to use this for 2 different Udemy accounts?

### ISSUE THREAD

**Issue by chaoscreater** [aapatre/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE#358]
I created 2 folders and in each folder, I've created a settings.yaml file with account logins for the 2 different accounts. When I run the script, it doesn't seem to use the account logins from the yaml file. It seems to only look at the account logins from here - `C:/Users/CurrentUserName/.udemy_enroller`

So my question is, how can I make this work for multiple Udemy accounts?

**Comment by fakeid30** [comment]
This is not supported.

**Comment by chaoscreater** [comment]
OK well this seems like an easy fix? Rather than saving the settings to `C:/Users/CurrentUserName/.udemy_enroller`, can't it just save the setting to the folder locally? That way, we can just create multiple folders and have a setting file for each folder. I'm not a programmer, but I imagine it's just a one line edit in your Python script?
