### ISSUE TITLE
New feature: Enroll only if it's a language you want

### ISSUE THREAD

**Issue by Sacrezar** [aapatre/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE#36]
It might be interesting to be able to choose if we add a course on udemy based on the language.

**Comment by cullzie** [comment]
Hey @Sacrezar, This is a great idea. I have created a PR for it. Let me know if that's what you had in mind

**Comment by Sacrezar** [comment]
Hey, that's it @cullzie 😊

**Comment by fakeid30** [comment]
This has now been solved thanks to @cullzie
