### ISSUE TITLE
[BUG] Exception in redeem courses: Message: unknown error: Cannot construct KeyEvent from non-typeable key

### ISSUE THREAD

**Issue by ruquistruquis** [aapatre/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE#364]
**Describe the bug**
When running udemy_enroller, a WebDriver error occurs **if** you have your keyboard set to a non-English layout.

**To Reproduce**
1. Run udemy enroller, e.g. `udemy_enroller --browser chromium --max-pages 2`
2. See error: 

```
Loading existing settings

====== WebDriver manager ======
Current chromium version is 98.0.4758
Get LATEST chromedriver version for 98.0.4758 chromium
Driver [/home/USER_NAME/.wdm/drivers/chromedriver/linux64/98.0.4758.80/chromedriver] found in cache
Exception in redeem courses: Message: unknown error: Cannot construct KeyEvent from non-typeable key
  (Session info: chrome=98.0.4758.80)
```

**Expected behavior**
udemy_enroller running and enrolling to different courses.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Debian 11 + KDE 5.20
 - Browser: Chromium
 - Version: 98.0.4758.80

**Additional context**
Searching around, it seems that webdriver changed something in the way it inputs text, so now if you have your keyboard layout set to something else than English (e.g., LatAm Spanish), it can raise an error when trying to input the @ character (see: https://github.com/zenstruck/browser/issues/66 ). Changing my keyboard layout to US-en "fixes" the problem, but I'd love not to change my keyboard layout.

**Comment by cullzie** [comment]
@ruquistruquis Thanks for raising this.
I've seen that pinning the driver version to 97 prevents this issue.
Another option is to send the keys in an ActionChain. My guess is this is specific to the @ symbol so it should only be needed on the email and possibly password entry

**Comment by cullzie** [comment]
Actually I just found this bug on it https://bugs.chromium.org/p/chromedriver/issues/detail?id=3999
and from looking at the comments the latest version of the driver resolves the issue.

**Comment by ruquistruquis** [comment]
Yeah, it seems solved by now. Webdriver version 98.0.4758.102 is working fine with my keyboard layout. Thanks for keeping an eye on this, and for this program too!
