### ISSUE TITLE
[BUG] Exception in redeem courses: 'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by pinguluk** [aapatre/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE#377]
![image](https://user-images.githubusercontent.com/16257821/170469622-d77dc1aa-2a8e-4562-bcda-711d7210b2b1.png)

**Comment by Asifjalil99** [comment]
facing same issue

**Comment by cullzie** [comment]
Using the REST api is experimental and is not stable. 
Please use with `--browser=chrome` as suggested for a stable experience.

**Comment by cullzie** [comment]
@pinguluk Latest version 4.1.1 should resolve this.
