### ISSUE TITLE
[BUG] ERROR runner : Timeout on link: 

### ISSUE THREAD

**Issue by MesterPerfect** [aapatre/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE#381]
hi 
After running udemy_enroller with the command```udemy_enroller --browser=chrome```
Log in with my udemy account and start browsing courses
But he doesn't get any and the log is filled with this message

```
2022-05-27 05:34:06,493 - udemy_enroller - ERROR - runner : Timeout on link: https://www.udemy.com/course/complete-excel-megacourse-beginner-to-expert/?couponCode=86C9E731CF00F71AEF98
```

**Desktop (please complete the following information):**
 - OS: [windows8.1]
 - Browser [chrome]
 - Version [102]

**Comment by cullzie** [comment]
Hey @MesterPerfect
Could you see what was happening in the browser at this time?

**Comment by MesterPerfect** [comment]
> Hey @MesterPerfect Could you see what was happening in the browser at this time?

Of course, it switches between courses without anything happening

**Comment by cullzie** [comment]
Thanks @MesterPerfect. Ok sounds like an xpath change then. I'll try have a look soon.

**Comment by MesterPerfect** [comment]
> Thanks @MesterPerfect. Ok sounds like an xpath change then. I'll try have a look soon.

ok, thanks

**Comment by cullzie** [comment]
@MesterPerfect I've updated the xpaths for the UI version.
 v4.1.2 has the changes. Could you please download and check things are working again. Thanks

**Comment by harmitstar** [comment]
latest master branch works for me.  Thank you for efforts
