### ISSUE TITLE
[BUG] Does not finish the free purchase

### ISSUE THREAD

**Issue by bmacedomadison1610** [aapatre/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE#384]
is arriving at the checkout screen but does not complete the free purchase automatically, having to do it manually for each course, after a few seconds it goes to another course search without finalizing.

**Comment by harmitstar** [comment]
Same here, have started facing this issue. Earlier it used to work perfectly.

**Comment by MesterPerfect** [comment]
> is arriving at the checkout screen but does not complete the free purchase automatically, having to do it manually for each course, after a few seconds it goes to another course search without finalizing.

This is exactly what happens to me
And I'm already completing the process to get the free offer manually
It remains like this until the browser window is closed, and a message appears in cmd stating that the work has finished

**Comment by cullzie** [comment]
I've updated the xpaths for the UI version. v4.1.2 has the changes. Could you please download and check things are working again. Thanks

**Comment by bmacedomadison1610** [comment]
least in my case, it still has the same problem does not finish the free purshase

**Comment by cullzie** [comment]
Hey @bmacedomadison1610,
Could you fill in the details required for a bug report please. Also could you let me know what country version of udemy you are using? 
It's possible there is a regional difference
Is the cli version working for you?

**Comment by MesterPerfect** [comment]
> Hey @bmacedomadison1610, Could you fill in the details required for a bug report please. Also could you let me know what country version of udemy you are using? It's possible there is a regional difference Is the cli version working for you?

Me too, still the same problem

**Comment by MesterPerfect** [comment]
> Hey @bmacedomadison1610, Could you fill in the details required for a bug report please. Also could you let me know what country version of udemy you are using? It's possible there is a regional difference Is the cli version working for you?

 For you, would it be good if I took a screenshot to clarify the problem
what do you think about this

**Comment by cullzie** [comment]
@MesterPerfect Ye that would help. As well as the language being used and region for udemy.

**Comment by MesterPerfect** [comment]
> @MesterPerfect Ye that would help. As well as the language being used and region for udemy.

I will make a video explaining the problem
I use udemy in English and my region is Egypt

**Comment by hobotheclown** [comment]
As far as I know, the check out page has changed when the course is free with the coupon code.  Before, it would go to the checkout page where you had to enter a zip code, payment info and the button was named  Complete Checkout . But now it takes you to a different page where it says your cart is free and the checkout button is named Free Purchase.

**Comment by bmacedomadison1610** [comment]
![page 1](https://user-images.githubusercontent.com/86125099/172022030-dd582aff-42a2-4614-9b51-deaa5d619bef.png)
![page 2](https://user-images.githubusercontent.com/86125099/172022033-d80b9aac-5245-4695-b96f-b50568f27c44.png)

**Comment by MesterPerfect** [comment]
@harmitstar
@hobotheclown
@bmacedomadison1610

This is a video that shows the problem
https://files.fm/f/rjsmmzt4u

cmd log 

```
Microsoft Windows [Version 6.3.9600]
(c) 2013 Microsoft Corporation. All rights reserved.

C:\Windows\system32>udemy_enroller --browser=chrome
Loading existing settings

[WDM] - ====== WebDriver manager ======
[WDM] - Current google-chrome version is 102.0.5005
[WDM] - Get LATEST chromedriver version for 102.0.5005 google-chrome
[WDM] - Driver [C:\Users\MesterPerfect\.wdm\drivers\chromedriver\win32\102.0.500
5.61\chromedriver.exe] found in cache

DevTools listening on ws://127.0.0.1:61218/devtools/browser/dc6c16b1-6323-4ef6-a
632-f9156b5324cc
freebiesglobal scraper is running
tutorialbar scraper is running
discudemy scraper is running
coursevania scraper is running
Page: 1 of 1245 scraped from tutorialbar.com
Page: 1 of 430 scraped from discudemy.com
Got 15 links from https://discudemy.com in 4.11 seconds
Got 12 links from https://www.tutorialbar.com in 7.95 seconds
Page: 1 of 441 scraped from coursevania.com
Got 12 links from https://coursevania.com in 8.59 seconds
Page: 1 of 1688 scraped from freebiesglobal.com
Got 30 links from https://freebiesglobal.com in 28.59 seconds
Timeout on link: https://www.udemy.com/course/youtube-podcast-marketing-for-natu
ral-health-practitioners/?couponCode=YTPMFNHPEXPJUN082022
Timeout on link: https://www.udemy.com/course/car-repair-auto-mechanic-training/
?couponCode=100OFFOCSALY
Timeout on link: https://www.udemy.com/course/the-ultimate-ethical-hacking-linux
-and-metasploit-training/?couponCode=100OFFOCSALY
Timeout on link: https://www.udemy.com/course/google-associate-cloud-engineer-gc
p-ace-exams/?couponCode=JUNEDROP2
Exiting the script
Closing browser

C:\Windows\system32>
```

**Comment by bmacedomadison1610** [comment]
this one I recorded with the brazil account, but I also tested it with the american account, both are the same bug

https://user-images.githubusercontent.com/86125099/172022396-1af8cde1-c971-466a-bf2a-e9ced484b33f.mp4

**Comment by hobotheclown** [comment]
I uninstalled and then reinstalled Python my system, I went through the steps again , installed requirements and installed udemy_enroller from the command line.

I kicked of the command udemy_enroller --browser=chrome.  It is working now for me.  When it gets to the free page, it will 'click' on the button now.  After the enroller completed, it shows I've enrolled some courses.

![image](https://user-images.githubusercontent.com/31145283/172299702-7cc3eb93-308d-4409-8434-8687e94b27f3.png)

**Comment by MesterPerfect** [comment]
I can't remove and install python again because I use many different libraries and services
I uninstalled udemy_enroller using pip and then re-installed it and the problem is not resolved

**Comment by hobotheclown** [comment]
> I can't remove and install python again because I use many different libraries and services I uninstalled udemy_enroller using pip and then re-installed it and the problem is not resolved

I don't have much libraries so it was ok for me to uninstall python as I'm learning python still.  I had different versions running, 3.7, 3.9, 3.10.  When I updated 3.9 to 3.10,  I didn't realize my 3.9 was from MSFT store.  After uninstalling, with 3.10 installed already it wouldn't work still.  I tried repairing the Python install after uninstall Anaconda, python 3.7 and python 3.9 (windows) it wouldn't even check which python -V it was.  

For me, in windows, the error msg said I had to go to Settings and App execution Aliases and turn on the app,  I don't remember the exact wording but this is the page.  I'm not sure why I have two python.exe showing on the list but after turning one off and leaving the other one, I was able to go to the command line and type python -V again showing version 3.10.

![image](https://user-images.githubusercontent.com/31145283/172464634-85206fcb-8023-4b4e-894f-82be6a6d4945.png)

I also tried to change/update the path in the environment variables before this and it didn't help.  Only doing so with the above method did it work for me.  VS Code was giving me a weird error saying I had to update user settings to use the 3.10 compiler when I tried to switch from version 3.9.   I think it was because of the python I installed through windows store.  Not too sure but I was able to get it all sorted out once I went to App execution aliases.  Unfortunately, this won't help users if they're on linux.

One thing though is I have never had the "Webdriver exception on link" error before.  It was always either a timeout or it just continued.  Still it is working so I am fine with this error. 

Hope that helps.

**Comment by hobotheclown** [comment]
For myself, I didn't have any issues anymore.  I redid everything and it worked.  Recently though, It stopped working.  I'm not sure if Udemy implemented a block/restriction on my account but I probably have logged in too much.  It's requiring me to verify that I am human which I believe was in past ticket.  I'll try again in a couple days to see if I still get the issue.  Thank you though for the response.
    On Friday, September 30, 2022 at 12:39:27 AM PDT, cullzie ***@***.***> wrote:  
 
 


Hey @bmacedomadison1610,
Apologies for missing the responses here.
Are you still having issues with this?

**Comment by cullzie** [comment]
Hey @hobotheclown, 
The CLI based enrollment should be a lot more stable than the UI based enrollment. I do not personally use the UI one ever only to fix issues with it. For the best experience I would recommend using the CLI flow.
You can have your account blocked (hasn't personally happened to me but has happened to others) so trying with another one is a quick way to determine if its the script or a Udemy ban.

**Comment by hobotheclown** [comment]
Thanks for the reply @cullzie.I never knew there was a difference between the CLI and UI.  I might have missed something going through the instructions.  Using windows, I see the command prompt window and it'll open up the chrome browser.  As it goes through the links, it will show some of the links in the command line sometimes and sometimes it wouldn't.  But chrome browser will go through each link.  I am wonder if that is the difference between UI and CLI.   I haven't ran the script for a few days now but will try again sometime this week.

    On Monday, October 17, 2022 at 08:09:10 AM PDT, cullzie ***@***.***> wrote:  
 
 


Hey @hobotheclown,
The CLI based enrollment should be a lot more stable than the UI based enrollment. I do not personally use the UI one ever only to fix issues with it. For the best experience I would recommend using the CLI flow.
You can have your account blocked (hasn't personally happened to me but has happened to others) so trying with another one is a quick way to determine if its the script or a Udemy ban.
