### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by hectoruelo** [aapatre/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE#392]
ubuntu  {>} python3 udemy_enroller.py 
**Loading existing settings
No cookie available
Exception in redeem courses: Unable to get csrf_token**

Linux server:
 ubuntu  {>} lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04 LTS
Release:        22.04
Codename:       jammy

 ubuntu  {>} python3 --version        
Python 3.10.4
 ubuntu  {>} 

Last script version

 ubuntu  {>} pip install -r requirements.txt 
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: aiohttp[speedups]==3.8.1 in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 1)) (3.8.1)
Requirement already satisfied: beautifulsoup4==4.11.1 in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 2)) (4.11.1)
Requirement already satisfied: ruamel.yaml==0.16.13 in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 3)) (0.16.13)
Requirement already satisfied: requests==2.27.1 in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 4)) (2.27.1)
Requirement already satisfied: cloudscraper==1.2.60 in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 5)) (1.2.60)
Requirement already satisfied: webdriver-manager==3.7.0 in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 6)) (3.7.0)
Requirement already satisfied: selenium==3.141.0 in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 7)) (3.141.0)
Requirement already satisfied: price-parser==0.3.4 in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 8)) (0.3.4)
Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in /usr/local/lib/python3.10/dist-packages (from aiohttp[speedups]==3.8.1->-r requirements.txt (line 1)) (4.0.2)
Requirement already satisfied: yarl<2.0,>=1.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp[speedups]==3.8.1->-r requirements.txt (line 1)) (1.7.2)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.10/dist-packages (from aiohttp[speedups]==3.8.1->-r requirements.txt (line 1)) (1.2.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/lib/python3/dist-packages (from aiohttp[speedups]==3.8.1->-r requirements.txt (line 1)) (21.2.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from aiohttp[speedups]==3.8.1->-r requirements.txt (line 1)) (1.3.0)
Requirement already satisfied: charset-normalizer<3.0,>=2.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp[speedups]==3.8.1->-r requirements.txt (line 1)) (2.0.12)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.10/dist-packages (from aiohttp[speedups]==3.8.1->-r requirements.txt (line 1)) (6.0.2)
Requirement already satisfied: Brotli in /usr/local/lib/python3.10/dist-packages (from aiohttp[speedups]==3.8.1->-r requirements.txt (line 1)) (1.0.9)
Requirement already satisfied: cchardet in /usr/local/lib/python3.10/dist-packages (from aiohttp[speedups]==3.8.1->-r requirements.txt (line 1)) (2.1.7)
Requirement already satisfied: aiodns in /usr/local/lib/python3.10/dist-packages (from aiohttp[speedups]==3.8.1->-r requirements.txt (line 1)) (3.0.0)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.10/dist-packages (from beautifulsoup4==4.11.1->-r requirements.txt (line 2)) (2.3.2.post1)
Requirement already satisfied: idna<4,>=2.5 in /usr/lib/python3/dist-packages (from requests==2.27.1->-r requirements.txt (line 4)) (3.3)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/lib/python3/dist-packages (from requests==2.27.1->-r requirements.txt (line 4)) (1.26.5)
Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python3/dist-packages (from requests==2.27.1->-r requirements.txt (line 4)) (2020.6.20)
Requirement already satisfied: requests-toolbelt>=0.9.1 in /usr/local/lib/python3.10/dist-packages (from cloudscraper==1.2.60->-r requirements.txt (line 5)) (0.9.1)
Requirement already satisfied: pyparsing>=2.4.7 in /usr/lib/python3/dist-packages (from cloudscraper==1.2.60->-r requirements.txt (line 5)) (2.4.7)
Requirement already satisfied: python-dotenv in /usr/local/lib/python3.10/dist-packages (from webdriver-manager==3.7.0->-r requirements.txt (line 6)) (0.20.0)
Requirement already satisfied: pycares>=4.0.0 in /usr/local/lib/python3.10/dist-packages (from aiodns->aiohttp[speedups]==3.8.1->-r requirements.txt (line 1)) (4.2.1)
Requirement already satisfied: cffi>=1.5.0 in /usr/local/lib/python3.10/dist-packages (from pycares>=4.0.0->aiodns->aiohttp[speedups]==3.8.1->-r requirements.txt (line 1)) (1.15.1)
Requirement already satisfied: pycparser in /usr/local/lib/python3.10/dist-packages (from cffi>=1.5.0->pycares>=4.0.0->aiodns->aiohttp[speedups]==3.8.1->-r requirements.txt (line 1)) (2.21)

¿Any idea?

**Comment by zemmsoares** [comment]
Grabbing google-chrome, manual login first and then run with `--browser=google-chrome` flag fixed it for me.

**Comment by hectoruelo** [comment]
Works ! Thks
