### ISSUE TITLE
Unable to Get CSRF_TOKEN

### ISSUE THREAD

**Issue by devarshishimpi** [aapatre/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE#394]
Hi,

Can someone help me with this?
Everything in the config is working correct, but when I use it, it crashes here.

Thanks.

![image](https://user-images.githubusercontent.com/43378923/188672902-29ea7a50-c66b-403d-a52a-1e1b0b178adb.png)

**Comment by devarshishimpi** [comment]
@cullzie Could You help me with this?

**Comment by cullzie** [comment]
Hey @devarshishimpi, the scripts are working for me.
 Can you try pull the latest version of the code please? This was an issue a few months ago from what I remember.

**Comment by devarshishimpi** [comment]
> Hey @devarshishimpi, the scripts are working fine for me. Can you pull the latest version of the code please? This was an issue a few months ago from what I remember.

Hi @cullzie , Yes, I am using the latest code version. The program was working fine without any issues till yesterday. Tried reinstalling and all kinds of similar stuff.

Can You link me to the previous issue if I can find something there which helps me out?

**Comment by cullzie** [comment]
Hey @devarshishimpi, The previous issue was to do with a code change that was required. 
Being unable to get this token is usually because the cloudflare captcha is being triggered. Maybe if you can try with/without a vpn it might help things

**Comment by devarshishimpi** [comment]
> Hey @devarshishimpi, The previous issue was to do with a code change that was required. Being unable to get this token is usually because the cloudflare captcha is being triggered. Maybe if you can try with/without a vpn it might help things

@cullzie Ah Okay, Thanks For Your Help. Was using a self-hosted VPN on AWS. Will try without it.

**Comment by devarshishimpi** [comment]
Thank You. It worked.
