### ISSUE TITLE
Courses aren't getting added because of ZIP code requirement

### ISSUE THREAD

**Issue by jimpallomeni** [aapatre/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE#4]
The Courses aren't getting added for me because the checkout is looking for a ZIP code. I am using macOS and Chrome. 
Please let me know if you need more information.
 
<img width="1440" alt="Screen Shot 2020-09-26 at 9 14 09 AM (2)" src="https://user-images.githubusercontent.com/11772520/94343952-1eec2500-ffd9-11ea-8d0a-2085dd3a09cd.png">

**Comment by aapatre** [comment]
@diflartle has contributed to the code and solved the issue, please clone and check again.

**Comment by aapatre** [comment]
Zip code functionality upgraded by @ethankrein

**Comment by jimpallomeni** [comment]
The zip code is working now. I also like the text file to put in your creds, it is much easier to use. Thanks for adding this so quickly.

**Comment by aapatre** [comment]
You are welcome! Added more updates: the webdrivers are now installed automatically based on the files chosen, and updated the docs
