### ISSUE TITLE
[BUG] HTTP error while loading existing course details

### ISSUE THREAD

**Issue by Voulz** [aapatre/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE#405]
Everything was working great until a few weeks ago and I haven't been able to run udemy_enroller since.
I get an error:
```
Loading existing settings  
No cookie available  
Caching cookie for future use  
Loading existing course details  
HTTP error while trying to fetch Udemy information  
404 Client Error: Not Found for url: https://www.udemy.com/api-2.0/users/me/subscribed-courses/?ordering=-last_accessed&fields%5Bcourse%5D=@min,enrollment_time,published_title,&fields%5Buser%5D=@min&page=24&page_size=100  
Unable to fetch existing courses. Login was not successful  
Exception in redeem courses: 404 Client Error: Not Found for url: https://www.udemy.com/api-2.0/users/me/subscribed-courses/?ordering=-last_accessed&fields%5Bcourse%5D=@min,enrollment_time,published_title,&fields%5Buser%5D=@min&page=24&page_size=100
```

There seems to be an issue with this URL:
`https://www.udemy.com/api-2.0/users/me/subscribed-courses/?ordering=-last_accessed&fields%5Bcourse%5D=@min,enrollment_time,published_title,&fields%5Buser%5D=@min&page=24&page_size=100`  
as it returns `{"detail":"Invalid page."}`
Interestingly, if I manually try to get the page 23 instead of 24, I get a proper response from the API `{"count":2300,"next":null,"previous": ...}`
We can also see that I have exactly 2300 enrolled courses, which is why the page 24 returns an error.
I'll have a look at the code when I get some time to try to understand why

**Tests**
Things I tried:
- redownloading the repo
- changing password
- deleting the .cookie and the settings.yaml files
- clearing the cookies and tomporary files from my computer

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: default

**Comment by Oka4444** [comment]
Same with me and I tried the same things you did, the problem is these days there's a lot of discounts that i don't wanna miss

**Comment by madhu2456** [comment]
Same Issue. Please resolve this.
![image](https://user-images.githubusercontent.com/38308514/204086071-43b84d71-4453-4db3-8ee8-2641530ac741.png)
