### ISSUE TITLE
[BUG] No cookie available

### ISSUE THREAD

**Issue by CAINTECH** [aapatre/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE#407]
I am trying to use this for the first time but after entering email and pw it is giving this error.

No cookie available
Exception in redeem courses: Unable to get csrf_token

**Comment by Cwarcup** [comment]
Same here

**Comment by tynzer** [comment]
> I am trying to use this for the first time but after entering email and pw it is giving this error.
> 
> No cookie available Exception in redeem courses: Unable to get csrf_token

Yes I have same problem with windows

**Comment by tigecyclindamycin** [comment]
Same error: after running "udemy_enroller" > input and save username + password, I get:

Loading existing settings
No cookie available
Exception in redeem courses: Unable to get csrf_token

**Comment by cullzie** [comment]
Hey All,
I am not seeing this issue. 
Are you running the latest version of the library? (4.1.2)
Are you running behind a vpn? This can sometimes cause issues.

**Comment by Oka4444** [comment]
same here
`> python3 udemy_enroller.py        
Loading existing settings
No cookie available
Exception in redeem courses: Unable to get csrf_token`

**Comment by cullzie** [comment]
Unfortunately until I have the issue I cannot do much about this one. Usually this is a sign that some changes are rolling out but only for specific regions. Can you tell me what region you are in @Oka4444  @wxifuwu ? Maybe I could reproduce with a vpn

**Comment by CAINTECH** [comment]
@cullzie India

**Comment by daverck** [comment]
This issue is the same as https://github.com/aapatre/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE/issues/409

**Comment by saifeealii** [comment]
same here. i was on a VPN and i turned it off but still getting the same error.
`Loading existing settings
No cookie available
Exception in redeem courses: Unable to get csrf_token`

**Comment by saifeealii** [comment]
> same here. i was on a VPN and i turned it off but still getting the same error. `Loading existing settings No cookie available Exception in redeem courses: Unable to get csrf_token`

i tried running it with the browser argument and it seems like that it's triggering the captcha and i am not able to login in the window that's opened and when i try to go to udemy homepage in that window, it goes to that typical checking browser page and it never loads. most likely udemy has made changes.

**Comment by compukation** [comment]
same here, I haven't found .cookies in .udemy_enroller, maybe the script isn't creating

**Comment by baba-boota** [comment]
> I am trying to use this for the first time but after entering email and pw it is giving this error.
> 
> No cookie available Exception in redeem courses: Unable to get csrf_token

it's working now. use @Asunnya's commit or just the developer branch.

**Comment by PrynsTag** [comment]
I am still encountering the error even if I use @Asunnya's commit.

```
(venv) C:\udemy_enroller> python .\udemy_enroller.py                   
Loading existing settings
No cookie available
Exception in redeem courses: Unable to get csrf_token
```

**Comment by MuhammadAmir1** [comment]
still not working with dev branch too. Exception in redeem courses: Unable to get csrf_token. I've tried in windows, linux, with python 3.11, 3.10,3.8. but all failed. same cookie error I manually created .cookie file then this works fine. but .cookie file not created automatically.

**Comment by baba-boota** [comment]
> still not working with dev branch too. Exception in redeem courses: Unable to get csrf_token. I've tried in windows, linux, with python 3.11, 3.10,3.8. but all failed. same cookie error I manually created .cookie file then this works fine. but .cookie file not created automatically.

get it from the release history and then update the udemy_rest.py file as in the dev branch. it's not working for me anymore though. i am now getting this error:

`HTTP error while trying to fetch Udemy information
403 Client Error: Forbidden for url: https://www.udemy.com/api-2.0/users/me/subscribed-courses/?ordering=-last_accessed&fields%5Bcourse%5D=@min,enrollment_time,published_title,&fields%5Buser%5D=@min&page=1&page_size=100
Unable to fetch existing courses. Login was not successful
Exception in redeem courses: 403 Client Error: Forbidden for url: https://www.udemy.com/api-2.0/users/me/subscribed-courses/?ordering=-last_accessed&fields%5Bcourse%5D=@min,enrollment_time,published_title,&fields%5Buser%5D=@min&page=1&page_size=100`

it looks like the request is being blocked now. udemy has made changes like more captchas probably.

**Comment by cullzie** [comment]
The latest version (4.1.3) has just been released to master and pypi.
Please let me know if the issues above have been resolved. Thanks

**Comment by matalve** [comment]
Still have the same issue unfortunately.

$ udemy_enroller
Loading existing settings
No cookie available
Exception in redeem courses: Unable to get csrf_token

**Comment by cullzie** [comment]
@matalve Could you please confirm you are on the latest version?
Running with `udemy_enroller --debug` should output the version details. 
If not you you are likely on the older version of the library. In which case can you check with pip to see the version installed. Thanks

**Comment by matalve** [comment]
> @matalve Could you please confirm you are on the latest version? Running with `udemy_enroller --debug` should output the version details. If not you you are likely on the older version of the library. In which case can you check with pip to see the version installed. Thanks

You are absolutely correct, after "pip install udemy_enroller -U" it works again. Thank you very much for you good work.
