### ISSUE TITLE
[Many Users Enrolling to the same Course]

### ISSUE THREAD

**Issue by jtheanalytica** [aapatre/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE#408]
**Describe the solution you'd like**
I'd like to have the following feature:
I have **80 Udemy usernames**.
I want the 80 users to enroll in the same Free Udemy course.

How to modify your code to be able to do that?

Basically what the script should do is:
Step1: Goto the Udemy link with the free coupon:
https://www.udemy.com/course/course-name/?couponCode=code

Step2: click the "Enroll now" button

Step 3: The browser will be directed to the signup form.
Step 4: Fill in the "Full Name", "email" and "Password. Then hit the signup button

Step 5: The browser will be directed to the page with "enroll" now. The user will be enrolled.

Step 6: Logout

Step 7: Repeat the previous steps for the next user in the list.

Thanks.

**Comment by cullzie** [comment]
Hey @jtheanalytica, This is not a feature we are going to implement. We do not support signup of emails in this script.
It could be used for gaming of udemy (eg. signup new accounts and subscribe to courses which could be used to boost popularity and ratings)
