### ISSUE TITLE
Enhancement: Regroup all code in one

### ISSUE THREAD

**Issue by Sacrezar** [aapatre/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE#41]
To facilite maintenance, I think it would be better to don't have duplicate code for each browser.

In this case, we could use the yaml to choose which browser we want to use

**Comment by fakeid30** [comment]
Our firefox code needs to be fixed to facilitate driver autoinstallation before we can merge all.

**Comment by ethankrein** [comment]
As fake said, we have some issues that need to be sorted on a per-browser basis before we can consolidate our code.

We have previously built a core for the project, but troubleshooting was much harder when building from it. After we tackle the larger issues expect to see dedicated corelogic for this project.

**Comment by fakeid30** [comment]
@Sacrezar we have started doing it eloquently now. Check #60 for more.
