### ISSUE TITLE
Enhancement: Automate Settings

### ISSUE THREAD

**Issue by Sacrezar** [aapatre/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE#42]
When you launch the script, if there is no setting available, it creates one and asks you your informations.

That way, the user just have to launch the script without worrying to check any other file.

**Comment by fakeid30** [comment]
This is a good idea.

**Comment by ethankrein** [comment]
@fakeid30 I have something like this coming for when we hit the cli marker.

**Comment by fakeid30** [comment]
@Sacrezar PR #60 fixes this issue.
