### ISSUE TITLE
[BUG] Unable to locate element: {"method":"css selector","selector":"[name="submit"]"}

### ISSUE THREAD

**Issue by rondotcomYT** [aapatre/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE#437]
**Describe the bug**
When passing the argument ```udemy_enroller --browser=chrome```, the following message occurs: ```Exception in redeem courses: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[name="submit"]"}```

**To Reproduce**
1. Run ```udemy_enroller --browser=chrome```
2. View output

**Desktop (please complete the following information):**
 - OS: Windows-10-10.0.19044-SP0
 - Browser: chrome=114.0.5735.134
 - Python Version: 3.11.4

**Additional Context**
Here is the full output:
```C:\Users\xx\Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE-master>udemy_enroller --browser=chrome
Name: udemy-enroller
Version: 4.1.3
Location: c:\users\xx\appdata\roaming\python\python311\site-packages
Python: 3.11.4 (tags/v3.11.4:d2340ef, Jun  7 2023, 05:45:37) [MSC v.1934 64 bit (AMD64)]
OS: Windows-10-10.0.19044-SP0
Loading existing settings

DevTools listening on ws://127.0.0.1:58488/devtools/browser/2c3a73e9-ad31-47ee-9d30-e96838a20af9
Exception in redeem courses: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[name="submit"]"}
  (Session info: chrome=114.0.5735.134)

Closing browser

**Comment by cullzie** [comment]
Hey @rondotcomYT,
Thanks for the report. The UI method of enrolling is no longer being maintained since it is prone to errors like this. Run the `udemy_enroller` command without specifying a browser
Please use the cli version and let me know if you have any issues with that.
Thanks
