### ISSUE TITLE
[BUG] list index out of range

### ISSUE THREAD

**Issue by Hussnain12** [aapatre/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE#441]
Error while running idownloadcoupon scraper: list index out of range
![image](https://github.com/aapatre/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE/assets/95158642/d591f6e9-42df-456d-8dc0-de8bcd43dad1)

**Desktop (please complete the following information):**
 - OS- Ubuntu 
 - Browser - default
 - Version 23.04

**Comment by cullzie** [comment]
Thanks @Hussnain12 for reporting. 
Yes I think some sites we are scraping are no longer functional or have changed structure a bit so needs a code change to resolve
