### ISSUE TITLE
Fix restyled-io bot

### ISSUE THREAD

**Issue by cullzie** [aapatre/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE#52]
At the moment there are too many checks and each one is restyling the last checks commit

Example:
isort changes the import to:
```
from selenium.common.exceptions import NoSuchElementException, TimeoutException
```

reorder-python-imports changes it back to:
```
from selenium.common.exceptions import NoSuchElementException
from selenium.common.exceptions import TimeoutException
```

And this is just repeated on every single PR

Can we reduce down the list of checks to `black` and `isort`?

**Comment by fakeid30** [comment]
@aapatre you can configure it .

**Comment by fakeid30** [comment]
@aapatre any update ?

**Comment by aapatre** [comment]
Not sure about how it could be done, since there aren't much options/settings for the restyled bot

**Comment by fakeid30** [comment]
https://github.com/restyled-io/restyled.io/wiki/Configuring-Restyled does this help ? @aapatre
