### ISSUE TITLE
Use f-strings instead of .format and string addition

### ISSUE THREAD

**Issue by Vthechamp22** [aapatre/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE#53]
Using [f-strings](https://realpython.com/python-f-strings/) which are available from Python 3.6 or greater is a very helpful and human-readable tool for string concatenation.

For example, in [line 141 to 142](https://github.com/aapatre/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE/blob/master/udemy_enroller_edge.py#L141-L142) in `udemy_enroller_edge.py`, you have to manually make page into a string:
```py
url = "https://www.tutorialbar.com/all-courses/" + "page/" + str(
            page) + "/"
```

This can be simplified using f-strings:
```python
url = f"https://www.tutorialbar.com/all-courses/page/{page}"
```

**Comment by fakeid30** [comment]
@Vthechamp22 This issue has been solved with PR #60
