### ISSUE TITLE
selenium.common.exceptions.WebDriverException: 

### ISSUE THREAD

**Issue by SibilinoNN** [aapatre/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE#6]
I get this error after running udemy_automate_course_enroll_v1.py , driver is in the system path I have already checked as per the instructions given here, Edge driver and browser match, I have already restarted. (https://www.selenium.dev/documentation/en/selenium_installation/installing_webdriver_binaries/). Please help!

This is how modified lines are set:
path = "C:\Webdriver\bin\msedgedriver.exe" 
driver = webdriver.Edge(path)  

This is the result:

"C:\Webdriver\bin\udemy_automate_course_enroll_v1.py"
Traceback (most recent call last):
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\common\service.py", line 72, in start
    self.process = subprocess.Popen(cmd, env=self.env,
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
**FileNotFoundError: [WinError 2] The system cannot find the file**

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Webdriver\bin\udemy_automate_course_enroll_v1.py", line 53, in <module>
    driver = webdriver.Edge(path)   # webdriver.Chrome(path) for Google Chrome, webdriver.Firefox(path) for Mozilla Firefox, webdriver.Edge(path) for Microsoft Edge, webdriver.Safari(path) for Apple Safari
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\edge\webdriver.py", line 56, in __init__
    self.edge_service.start()
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\common\service.py", line 81, in start
    **raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: 'msedgedriver' executable needs to be in PATH. Please download from http://go.microsoft.com/fwlink/?LinkId=619687**

Fixed this for edge and firefox, using a different Line 54 however now I get this:

**Unable to enroll for this course either because you have already claimed it or the browser window has been closed
Unable to enroll for this course either because you have already claimed it or the browser window has been closed
Unable to enroll for this course either because you have already claimed it or the browser window has been closed
Unable to enroll for this course either because you have already claimed it or the browser window has been closed
Unable to enroll for this course either because you have already claimed it or the browser window has been closed
Unable to enroll for this course either because you have already claimed it or the browser window has been closed**

**Comment by SibilinoNN** [comment]
Went around the issue using geckodriver and firefox, and I have been able to set it up successfully.

The script is now running However now I get this error for every course I want to enroll:

Unable to enroll for this course either because you have already claimed it or the browser window has been closed!

No error code, however when I open up geckodriver log, this comes up:

1601145180971	geckodriver	INFO	Listening on 127.0.0.1:50491
1601145184006	mozrunner::runner	INFO	Running command: "C:\\Program Files\\Firefox Nightly\\firefox.exe" "--marionette" "-foreground" "-no-remote" "-profile" "C:\\Users\\Usuario\\AppData\\Local\\Temp\\rust_mozprofileFrzpHs"
Can't find symbol 'eglSwapBuffersWithDamageEXT'.
console.warn: SearchSettings: "get: No settings file exists, new profile?" (new Error("", "(unknown module)"))
1601145187371	Marionette	INFO	Listening on port 50499
1601145187635	Marionette	WARN	TLS certificate errors will be ignored for this session
JavaScript error: https://www.udemy.com/staticx/udemy/js/webpack/entry-udlite-baseline-modern-vendor.17b8253c597a02d977be.js, line 1: Error: Request aborted
JavaScript error: https://www.udemy.com/staticx/udemy/js/webpack/entry-udlite-baseline-modern-vendor.17b8253c597a02d977be.js, line 1: Error: Request aborted
JavaScript error: https://www.udemy.com/staticx/udemy/js/webpack/entry-udlite-baseline-modern-vendor.17b8253c597a02d977be.js, line 1: Error: Request aborted
JavaScript error: https://www.udemy.com/staticx/udemy/js/webpack/entry-udlite-baseline-modern-vendor.17b8253c597a02d977be.js, line 1: Error: Request aborted
JavaScript error: https://www.udemy.com/staticx/udemy/js/webpack/entry-udlite-baseline-modern-vendor.17b8253c597a02d977be.js, line 1: Error: Request aborted
JavaScript error: https://www.udemy.com/staticx/udemy/js/webpack/entry-udlite-baseline-modern-vendor.17b8253c597a02d977be.js, line 1: Error: Request aborted
JavaScript error: https://www.udemy.com/staticx/udemy/js/webpack/entry-udlite-baseline-modern-vendor.17b8253c597a02d977be.js, line 1: Error: Request aborted
JavaScript error: https://www.udemy.com/staticx/udemy/js/webpack/entry-udlite-baseline-modern-vendor.17b8253c597a02d977be.js, line 1: Error: Request aborted
JavaScript error: https://www.udemy.com/staticx/udemy/js/webpack/entry-udlite-baseline-modern-vendor.17b8253c597a02d977be.js, line 1: Error: Request aborted
JavaScript error: https://www.udemy.com/staticx/udemy/js/webpack/entry-udlite-baseline-modern-vendor.17b8253c597a02d977be.js, line 1: Error: Request aborted
JavaScript error: https://www.udemy.com/staticx/udemy/js/webpack/entry-udlite-baseline-modern-vendor.17b8253c597a02d977be.js, line 1: Error: Request aborted
JavaScript error: https://www.udemy.com/staticx/udemy/js/webpack/entry-udlite-baseline-modern-vendor.17b8253c597a02d977be.js, line 1: Error: Request aborted
JavaScript error: https://www.udemy.com/staticx/udemy/js/webpack/entry-udlite-baseline-modern-vendor.17b8253c597a02d977be.js, line 1: Error: Request aborted
JavaScript error: https://www.udemy.com/staticx/udemy/js/webpack/entry-udlite-baseline-modern-vendor.17b8253c597a02d977be.js, line 1: Error: Request aborted
JavaScript error: https://www.udemy.com/staticx/udemy/js/webpack/entry-udlite-baseline-modern-vendor.17b8253c597a02d977be.js, line 1: Error: Request aborted
JavaScript error: https://www.udemy.com/staticx/udemy/js/webpack/entry-udlite-baseline-modern-vendor.17b8253c597a02d977be.js, line 1: Error: Request aborted
JavaScript error: https://www.udemy.com/staticx/udemy/js/webpack/entry-udlite-baseline-modern-vendor.17b8253c597a02d977be.js, line 1: Error: Request aborted
JavaScript error: https://www.udemy.com/staticx/udemy/js/webpack/entry-udlite-baseline-modern-vendor.17b8253c597a02d977be.js, line 1: Error: Request aborted

**Comment by aapatre** [comment]
Try again with a new clone of the repository. There are major improvements to the codes and the documentations!
Please report your status after trying it.

**Comment by fakeid30** [comment]
@SibilinoNN can you please pull in the latest code and update on this issue ? Thank you.

**Comment by SibilinoNN** [comment]
> 
> 
> Try again with a new clone of the repository. There are major improvements to the codes and the documentations!
> Please report your status after trying it.

Update has fixed this issue. Specifically adding pip install webdriver_manager as requirement

However, Code still isn't working as UDEMY ask me to confirm "Billing address", I have to  manually press the red "Inscríbete ya" (enroll)  button to be able to enroll but this defeat the purpose of the bot. (Look at the attached picture for more information)

https://imgur.com/HVzMnpB

Is there any way the bot could "press" the red "enroll" button?

**Comment by aapatre** [comment]
Looks like it works only on the English Udemy, maybe because the xpath
values for the buttons are different on both. That's currently the only
explanation I can think of, as of now. Especially because it's missing the
secondary billing information (ZIP Code or State or another similar
counterpart). It's probably not required in Chile.

Try comparing the xpath in the code and your regional version of the site
with these steps and change it as you see fit:
https://www.scientecheasy.com/2020/07/find-xpath-chrome.html/

**Comment by ethankrein** [comment]
This error occurs because the XPATH is looking for id "udemy", but that id changes across languages.
`driver.find_element_by_xpath("//*[@id=\"udemy\"]`

<details> 
  <summary>IDs by language:</summary>

   **Deutsch:** de
   **English:** udemy
   **Español:** es
   **Français:** fr
   **Bahasa Indonesia:** udemy
   **Italiano:** udemy
   **日本語:** jp
   **한국어:** udemy
   **Nederlands:** udemy
   **Polski:** udemy
   **Português:** pt
   **Română:** udemy
   **Русский:** udemy
   **ภาษาไทย:** udemy
   **Türkçe:** udemy
   **中文(简体):** udemy
   **中文 (繁體):** udemy
</details>

5/17 languages do not use "udemy" as the id meaning the XPATH is invalid in ~29% of the languages Udemy supports. Two possible solutions I can think of:
* Add language id to the settings file and use that to determine the id needed in the XPATH
* Switching through all of the languages it appears that the body keeps the same class "udemy pageloaded"

**Comment by ethankrein** [comment]
I think I've got this solved. Mind giving a testrun to my language support branch?

https://github.com/ethankrein/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE/tree/Add-language-support

**Comment by fakeid30** [comment]
Wow bro fantastic.

**Comment by fakeid30** [comment]
I'll test this at night with spanish localization. If it works we can safely close this issue.

**Comment by ethankrein** [comment]
While we're still waiting for @SibilinoNN to confirm whether this solves the issue, I've submitted pr #20 with my fix. In testing it works in every language I listed that does not use "udemy" for the id as well as in English. I'm very confident that it will work for every localization and will await your testing.

**Comment by aapatre** [comment]
Great work @ethankrein 🎉
Did you use a VPN? If yes, which VPN did you use?
Hola isn't working for Udemy.

**Comment by ethankrein** [comment]
> Did you use a VPN? If yes, which VPN did you use?

All I had to do was change my language options in the account settings. https://www.udemy.com/user/edit-profile/

**Comment by fakeid30** [comment]
> While we're still waiting for @SibilinoNN to confirm whether this solves the issue, I've submitted pr #20 with my fix. In testing it works in every language I listed that does not use "udemy" for the id as well as in English. I'm very confident that it will work for every localization and will await your testing.

I confirm this seems to be working for me as well. Good job.

**Comment by aapatre** [comment]
Cool! 🤝

**Comment by fakeid30** [comment]
@SibilinoNN I am closing the issue as it seems to have been solved, if it is still an issue, please comment and reopen.
