### ISSUE TITLE
Using Poetry instead of requirements 

### ISSUE THREAD

**Issue by fakeid30** [aapatre/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE#61]
What do you think about that? @cullzie @aapatre @ethankrein 

https://python-poetry.org/

**Comment by cullzie** [comment]
@fakeid30 I usually use pipenv in projects I'm working on. Haven't used poetry but it seems to offer similar functionality.
It just boils down to personal preferences at the end of the day.
I'm all for adding something more functional for dev than requirements though :+1:

**Comment by fakeid30** [comment]
@cullzie In my arch linux I still face this issue : https://github.com/pypa/pipenv/issues/2681 , so I've went ahead and added Poetry . 

Invoking `poetry install` in the project directory should setup the environment now.
