### ISSUE TITLE
Get rid of html code in README

### ISSUE THREAD

**Issue by fakeid30** [aapatre/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE#64]
The readme file has some HTML code which needs to be gone (https://github.com/aapatre/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE#instructions)

**Comment by Shamiul419** [comment]
I have fixed this issue and sent a PR. Check if it work.

**Comment by fakeid30** [comment]
Thank you. It indeed fixes it.
