### ISSUE TITLE
Udemy antibot triggered

### ISSUE THREAD

**Issue by GodSaveTheDoge** [aapatre/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE#82]
For now udemy detects the bot and i'm unable to login (without completing a captcha) because it tries to change page too fast. After the login it should check and, if there is the captcha, wait until the captcha is completed (maybe just with `input("Please complete the captcha and press enter. ")`).

![screenshot](https://i.imgur.com/vEYAF4B.png)

**Comment by GodSaveTheDoge** [comment]
Also it's not consistent. Sometimes it happens, sometimes not. When it happens, restart and everything works again, like magic

**Comment by fakeid30** [comment]
@GodSaveTheDoge this is documented in FAQ , we have some mitigation in check in our Develop branch but we can't completely avoid it.
