### ISSUE TITLE
Trying to enroll in courses i'm already enrolled in

### ISSUE THREAD

**Issue by GodSaveTheDoge** [aapatre/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE#83]
Well the title says everything.
It could save links of courses it processed and skip them the next time you run it. It could also save the email address linked to these links to avoid deleting / moving the list to use multiple accounts.

**Comment by GodSaveTheDoge** [comment]
uhm, maybe instead of saving that, just check if the button says "Go to course"

**Comment by cullzie** [comment]
Ye I was thinking about this and it would be fairly simple to add a local cache. I'm thinking a simple dict in a file called `.cache` . 
Should we assume the cache is just for one user though or should there be a section in the cache for each email used?

**Comment by fakeid30** [comment]
@cullzie @GodSaveTheDoge multiple account seems like a niche case to me to be honest. we should make sure that we don't have feature creep.

**Comment by cullzie** [comment]
So would a simple file cache suffice (assuming 1 user)?

Basically just a list of dictionaries dumped to file:
```
{"url": "https://www.udemy.com/course/course-1/?couponCode=A832C5AE9510F68A8FC4", "status": "ENROLLED", "date": "2020-11-07T22:09:24.326497"}
{"url": "https://www.udemy.com/course/course-2/?couponCode=4534B77F23F94548F3BA", "status": "ENROLLED", "date": "2020-11-07T22:10:46.085615"}
```

Maybe an improvement or overkill but we could use sqlite3 and orm (sqlalchemy) which would mean the data is searchable/filterable if we wanted to generate stats in future for a user.

sqlite3 is builtin so no extra overhead

**Comment by fakeid30** [comment]
> Maybe an improvement or overkill but we could use sqlite3 and orm (sqlalchemy) which would mean the data is searchable/filterable if we wanted to generate stats in future for a user.

Yes this is a good idea, not overkill IMO. 

> sqlite3 is builtin so no extra overhead

yeah if we want a small ORM peewee is another option

**Comment by cullzie** [comment]
@fakeid30  Ye the simple cache is straightforward and conforms to the use case well
Stats can still be gotten from the file cache. Just it won't be as performant or as feature rich as a DB.

Regarding adding a DB it would be more involved (schemas, deployment, etc). 
It probably isn't needed at the moment anyway and would introduce more code to debug through

**Comment by fakeid30** [comment]
agreed.

**Comment by aapatre** [comment]
I've tried working on this previously, but it wasn't a successful attempt.
Your approach of using a cache seems pretty good. Is it possible to use a hashtable for increasing the speed of checks? (Especially when the user has enrolled to thousands of courses before)

**Comment by cullzie** [comment]
@aapatre I've opened #98 have a look and add any questions/improvements there :+1: 

At the moment we are using a dictionary for the cache which is already a hash lookup: https://stackoverflow.com/a/114831/6657098

**Comment by cullzie** [comment]
@fakeid30 @GodSaveTheDoge Is this ok to close? The caching and script should handle these scenarios more efficiently now

**Comment by GodSaveTheDoge** [comment]
yes, the problem was loading a page just to check if enrolled.
