### ISSUE TITLE
Adding filters

### ISSUE THREAD

**Issue by designjeevan** [aapatre/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE#84]
Hi. Kudos to the developers for their efforts. 
What about adding filters in the application for enrolling user to those courses according to the their intrest such as **4 stars or above**, those courses containing keywords like **excel**, **analytics**, **python**, and so on.

**Comment by fakeid30** [comment]
hello @designjeevan Check out #47 , we have deemed it low priority , but any PR is welcome. 

The reason we have deemed it low priority is because we are not trying to segregate courses. Some of the newer courses are decent.

**Comment by fakeid30** [comment]
@designjeevan now we have a way to select from development , music, design and so on. I think this is as far as we will go about doing this. So I'm closing it. If you have further query please comment here.
