### ISSUE TITLE
password problems

### ISSUE THREAD

**Issue by OmegaDL2** [aapatre/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE#85]
when I run the script and it asks me for the password, it won't let me type anything, like if the keyboard didn't work

**Comment by fakeid30** [comment]
@OmegaDL2 this is by design, just type/copy your password and press enter, this will register. 

Linux terminal also follows this design to prevent people from looking over and guess the password length.

**Comment by OmegaDL2** [comment]
OK, thank you
