### ISSUE TITLE
Message: 'geckodriver' executable needs to be in PATH.

### ISSUE THREAD

**Issue by flopezre** [aapatre/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE#86]
Hello, i have this problem:
![capture](https://user-images.githubusercontent.com/4932575/98440123-82d43400-20d5-11eb-814f-eb736814f77c.jpg)

Help please!

Cheers..

**Comment by fakeid30** [comment]
@flopezre hello , our firefox code needs manual intervention. You need to manually but the geckodriver in path following this tutorial : https://helpdeskgeek.com/windows-10/add-windows-path-environment-variable/

alternately , use the chrome / chromium version if the above solution is not feasible for you.
