### ISSUE TITLE
CI failing

### ISSUE THREAD

**Issue by fakeid30** [aapatre/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE#87]
![unknown](https://user-images.githubusercontent.com/26362832/98443123-81395900-2133-11eb-9197-d193a7931e98.png)

@cullzie CI seems to be failing even with a configured dummy account in secrets, we've given you collaborator status. Can you please check what seems to be the problem ?

**Comment by cullzie** [comment]
@fakeid30 Opened a PR for it :+1:
