### ISSUE TITLE
webdriver_manager no module found

### ISSUE THREAD

**Issue by tildesarecool** [aapatre/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE#9]
Using windows 10, python v3.8.3
attempted to run chrome script and got message
**ModuleNotFoundError: No module named 'webdriver_manager'**

I found a stack exchange page that to use this line:
**pip install webdriver_manager**

this successfully installed webdriver manager

**Comment by aapatre** [comment]
Is the code working now?

**Comment by tildesarecool** [comment]
I did eventually get the program to work. I think I also get that error when running on the CLI instead of through IDLE as instructed.

**Comment by aapatre** [comment]
It's weird that changing IDEs is leading to different errors. 🤔 Anyways, thanks for reporting!
