### ISSUE TITLE
Updating README

### ISSUE THREAD

**Issue by fakeid30** [aapatre/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE#93]
I think we need to change [FAQ #7](https://github.com/aapatre/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE#7-which-is-the-best-way-to-run-the-script)

Also once we incorporate develop into master and make a new release we need to remove the section about saved card.

**Comment by cullzie** [comment]
Ye before we do the next release we should review the README and see what needs to be done on this. There's probably a few bits which are no longer relevent
