### ISSUE TITLE
Stop trying after X number of failed requests  

### ISSUE THREAD

**Issue by fakeid30** [aapatre/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE#94]
When an user sees a page that they have redeemed before, it's unlikely that they will see any non redeemed course after. 

This issue proposes to see have the program terminated after X amount of failed attempt. The number can be user inputted or hard coded. I think 22 is a good number.

This is a finer version of PR #11

**Comment by cullzie** [comment]
@fakeid30 Well after the first run we know there are 580 pages on tutorialbar for example
So on the next run if we know the previous run had 580 pages and now we see 582 pages we should only scrape the first 3 pages (3 pages in case there is some overlap)

This assumes first run was good and completed in full and that tutorialbar never removes pages

If someone wants to rerun a full run they can just remove the previous runs page count

**Comment by fakeid30** [comment]
@cullzie yes this idea is also viable.

**Comment by cullzie** [comment]
@fakeid30 Ye that's the reason for the slight overlap 282 - 280 = 2 pages but we should scrape 3 to make sure we cover any partial pages

**Comment by fakeid30** [comment]
sounds good

**Comment by fakeid30** [comment]
@cullzie I think after we do this (if we decide to do this) we are feature complete and can release v1. Take a look at : https://github.com/aapatre/Automatic-Udemy-Course-Enroller-GET-PAID-UDEMY-COURSES-for-FREE/projects/1

**Comment by cullzie** [comment]
@fakeid30 Do you think this could be simplified down to if we hit the cache X times in a row then we should exit the script? Ignoring any exceptions which might arise because of bad links or timeouts?

**Comment by fakeid30** [comment]
Of course . Hitting cache 6-7 times in a
 row should be enough indication that there's nothing beyond that point.

**Comment by cullzie** [comment]
OK that should be straightforward in that case. Should we add a cli arg to pass the cache-hits limit? Something like `--cache-hits`  or should we leave that as an improvement after the initial implementation

**Comment by fakeid30** [comment]
Cache hits sounds better . Then we won't need to touch this later. 

So you suggest this ? 

`python udemy_enroller_firefox.py --max-pages=5 --cache-hits=5`

Whichever comes first?

**Comment by cullzie** [comment]
Ye `--cache-hits` or `--cache-hits-limit`. Not sure which one is better :smile: 
It should be straightforward to add everything in one

**Comment by fakeid30** [comment]
Cache hits sounds better to me. But I wonder if it'll be ambigous to normal users .

**Comment by cullzie** [comment]
Ye I was trying to be as verbose as possible with `--cache-hits-limit`
I doubt its something most people will make use of though and there will be a doc in argparse to explain its usage

**Comment by fakeid30** [comment]
then let's go with --cache-hits

After this we release 🚀 🔥
